"""The canonical vocabulary serialization, pinned to the file the browser stack reads.

Red-team F6. ``vocab_sha256`` is a digest of :meth:`GeoTokenizer.to_json`'s exact bytes, and
since a model's identity covers its vocabulary (commit ``0d23123``) that digest is part of
the model id. A serialization divergence therefore does not produce a cosmetic difference —
it produces two models where there is one, and the symptom is a good file being refused as
corrupt by the other stack.

The divergence was DEL. Python's ``ensure_ascii`` is not "escape non-ASCII": the encoder
keeps ``\\x20``-``\\x7e`` and escapes everything else, U+007F included. The browser's
``canonicalVocabJson`` tested ``code < 0x80`` and left DEL raw, so on a 1000-word list ending
in U+007F the two stacks produced ``927b4da6…`` and ``e2ebf087…``.

Both suites now assert against ONE transcript of the real Python serializer,
``code/frontend/tests/fixtures/geo-canonical-vocab.json``, regenerated by
``python scripts/export_geo_canonical_vocab.py``. This module is the half that keeps the
transcript honest: if Python's output moves, the fixture stops matching here, and the
browser test that reads the same file starts failing too.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from llm_geometry.geo.tokenizer import VOCAB_WORDS, GeoTokenizer

#: tests/unit/<this file> -> tests -> backend -> code -> repo root.
REPO_ROOT = Path(__file__).resolve().parents[4]
FIXTURE = REPO_ROOT / "code" / "frontend" / "tests" / "fixtures" / "geo-canonical-vocab.json"


def _fixture() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def test_the_fixture_is_this_serializers_own_output() -> None:
    """A transcript, not an expectation somebody typed."""
    fx = _fixture()
    assert fx["format"] == "geo-canonical-vocab-v1"
    assert fx["command"] == "python scripts/export_geo_canonical_vocab.py"
    assert len(fx["words"]) == VOCAB_WORDS

    canonical = GeoTokenizer(fx["words"]).to_json()
    assert canonical == fx["canonicalJson"]
    assert hashlib.sha256(canonical.encode("utf-8")).hexdigest() == fx["vocabSha256"]


def test_the_probe_words_are_the_characters_that_decide_the_question() -> None:
    """A fixture of ordinary words cannot see this defect: every word in the shipped
    vocabulary is ASCII-printable, so the two encoders agree on all of them."""
    fx = _fixture()
    assert "\x7f" in fx["probeWords"]
    assert any(len(w) > 1 and "\x7f" in w for w in fx["probeWords"])
    assert "~" in fx["probeWords"]
    for word in fx["probeWords"]:
        assert word in fx["words"]


def test_ensure_ascii_escapes_del_and_keeps_the_printable_ascii_either_side() -> None:
    """The boundary as a rule rather than as one example: ``\\x20``-``\\x7e`` survive, and
    everything else is escaped. ``code < 0x80`` satisfies every clause of this but the first,
    which is exactly how it passed review."""
    canonical = GeoTokenizer(_fixture()["words"]).to_json()
    assert "\\u007f" in canonical
    assert "\x7f" not in canonical
    assert '"~"' in canonical
    assert "\\u00e9" in canonical
    assert "\\ud83d\\ude00" in canonical
