/**
 * `canonicalVocabJson` produces Python's bytes, DEL included — red-team F6.
 *
 * `vocab_sha256` is a digest of the canonical vocabulary bytes, and since a model's
 * identity now covers its vocabulary (commit `0d23123`) the digest is part of the model id.
 * So a serialization divergence is not a formatting wart: it splits the model.
 *
 * The divergence was DEL. Python's `ensure_ascii` is not "escape non-ASCII" — its encoder
 * keeps `\x20`–`\x7e` and escapes everything else, U+007F included — and this function
 * tested `code < 0x80`, leaving DEL raw. Measured on a 1000-word list ending in U+007F:
 *
 *     PY vocab sha256   = 927b4da6…      TS vocab sha256   = e2ebf087…
 *     PY weights_token  = eaa10f1e…      TS weights_token  = adfa9a05…
 *
 * A file saved by the full stack was therefore refused by the static build as "this model
 * file is corrupt", and vice versa — a good file accused of corruption. The geo token regex
 * `[^\sa-z0-9]` admits any single non-space symbol, so DEL really can reach a word list.
 *
 * The fixture is a TRANSCRIPT of the real Python serializer, regenerated by
 *
 *     python scripts/export_geo_canonical_vocab.py
 *
 * and `code/backend/tests/unit/test_geo_canonical_vocab.py` asserts the live Python still
 * produces it. Neither stack can drift alone.
 */

import { describe, expect, it } from "vitest";

import { canonicalVocabJson } from "../../src/lib/geoEngine/tokenizer";
import fixture from "../fixtures/geo-canonical-vocab.json";

async function sha256Hex(text: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

describe("the canonical vocabulary serialization is byte-identical to Python's", () => {
  it("declares its format and its generator", () => {
    expect(fixture.format).toBe("geo-canonical-vocab-v1");
    expect(fixture.command).toBe("python scripts/export_geo_canonical_vocab.py");
    expect(fixture.words).toHaveLength(1000);
  });

  it("carries the characters that decide the question, DEL among them", () => {
    // A fixture of ordinary words could not see this defect at all.
    expect(fixture.probeWords).toContain("\u007f");
    expect(fixture.probeWords.some((w) => w.length > 1 && w.includes("\u007f"))).toBe(true);
    expect(fixture.probeWords).toContain("~");
    for (const w of fixture.probeWords) expect(fixture.words).toContain(w);
  });

  it("reproduces the real Python output character for character", () => {
    expect(canonicalVocabJson(fixture.words)).toBe(fixture.canonicalJson);
  });

  it("hashes to the digest Python computed, which is what the model id covers", async () => {
    expect(await sha256Hex(canonicalVocabJson(fixture.words))).toBe(fixture.vocabSha256);
  });

  it("escapes DEL and keeps the printable ASCII either side of it", () => {
    // The boundary itself, stated as a rule rather than as one example: `\x20`–`\x7e` stay,
    // everything else is escaped. `code < 0x80` passes every part of this but the first.
    const json = canonicalVocabJson(fixture.words);
    expect(json).toContain("\\u007f");
    expect(json).not.toContain("\u007f");
    expect(json).toContain('"~"');
    expect(json).toContain("\\u00e9");
    expect(json).toContain("\\ud83d\\ude00");
  });
});
