/**
 * Shared golden-asset loading for the geoEngine test suites.
 *
 * Assets resolve from public/static-data/geo/ (the static-site export) when
 * present, plus the committed real-backend fixtures in tests/fixtures/geo/
 * (generated by tests/fixtures/geo/generate.py: uvicorn + the backend's own geo
 * functions — nothing hand-written). Two golden schemas are understood:
 *   - the fixture schema ("geo-golden-v1": route request/response pairs), and
 *   - the static export schema ({cases, weight_edits, finetune}), normalized
 *     onto the fixture schema here.
 * The suites run against BOTH sources when both exist, cross-validating the two
 * independent exporters against the TS engine.
 */

import fs from "node:fs";
import path from "node:path";

export const STATIC_DIR = path.resolve(__dirname, "../../public/static-data/geo");
export const FIXTURE_DIR = path.resolve(__dirname, "../fixtures/geo");

export function loadJson(file: string): unknown {
  return JSON.parse(fs.readFileSync(file, "utf-8"));
}

/** Prefer the static-site export when it exists AND parses; else fixtures. */
export function loadAsset(name: string): unknown {
  const staticPath = path.join(STATIC_DIR, name);
  if (fs.existsSync(staticPath)) {
    try {
      return loadJson(staticPath);
    } catch (err) {
      console.warn(`static-data/geo/${name} exists but failed to parse; using fixtures`, err);
    }
  }
  return loadJson(path.join(FIXTURE_DIR, name));
}

export interface GoldenFile {
  format: string;
  spec: Record<string, any>;
  tokenize: { text: string; response: Record<string, any> }[];
  trace: { prompt: string; response: Record<string, any> }[];
  vector_field: { params: Record<string, any>; response: Record<string, any> }[];
  weights_get: { params: Record<string, any>; response: Record<string, any> }[];
  weights_post: { body: Record<string, any>; response: Record<string, any> }[];
  finetune: { body: Record<string, any>; result: Record<string, any> }[];
}

/**
 * Normalize the static-site export's golden schema ({cases: [{prompt, trace,
 * fields: [{params, response}]}], weight_edits, finetune}) onto GoldenFile.
 * Field params there omit the prompt (it is the case's); weight_edits carry the
 * minted token but no `edited` summaries (assertions treat `edited` as
 * optional); the spec golden is the exported spec.json.
 */
function normalizeStaticGolden(data: any): GoldenFile | null {
  if (!Array.isArray(data?.cases) || !Array.isArray(data?.weight_edits)) return null;
  let spec: Record<string, any>;
  try {
    spec = loadJson(path.join(STATIC_DIR, "spec.json")) as Record<string, any>;
  } catch {
    return null;
  }
  const trace: GoldenFile["trace"] = [];
  const vector_field: GoldenFile["vector_field"] = [];
  for (const c of data.cases) {
    trace.push({ prompt: c.prompt, response: c.trace });
    for (const f of c.fields ?? []) {
      vector_field.push({ params: { ...f.params, prompt: c.prompt }, response: f.response });
    }
  }
  const weights_post: GoldenFile["weights_post"] = data.weight_edits.map((w: any) => ({
    body: w.body,
    response: { weights_token: w.weights_token },
  }));
  const finetune: GoldenFile["finetune"] = [];
  const ft = data.finetune;
  if (ft && typeof ft.text === "string") {
    finetune.push({
      body: { text: ft.text, steps: ft.steps, lr: ft.lr, seed: ft.seed },
      result: {
        weights_token: ft.weights_token,
        loss_before: ft.loss_before,
        loss_after: ft.loss_after,
      },
    });
  }
  return {
    format: "geo-golden-v1(normalized-static)",
    spec,
    tokenize: [], // no tokenize goldens in the static export; trace.tokens are id-exact instead
    trace,
    vector_field,
    weights_get: [],
    weights_post,
    finetune,
  };
}

/** All golden sources (static export first when present, then the fixtures). */
export function loadGoldens(): GoldenFile[] {
  const sources: GoldenFile[] = [];
  const staticPath = path.join(STATIC_DIR, "golden.json");
  if (fs.existsSync(staticPath)) {
    try {
      const data = loadJson(staticPath) as any;
      if (data?.format === "geo-golden-v1" && Array.isArray(data.trace)) {
        sources.push(data as GoldenFile);
      } else {
        const normalized = normalizeStaticGolden(data);
        if (normalized) sources.push(normalized);
        else console.warn("static-data/geo/golden.json has an unrecognized schema; skipping it");
      }
    } catch (err) {
      console.warn("static-data/geo/golden.json failed to parse; skipping it", err);
    }
  }
  sources.push(loadJson(path.join(FIXTURE_DIR, "golden.json")) as GoldenFile);
  return sources;
}

/** One merged golden file spanning every available source. */
export function loadMergedGolden(): GoldenFile {
  const [first, ...rest] = loadGoldens();
  const merged: GoldenFile = {
    ...first,
    tokenize: [...first.tokenize],
    trace: [...first.trace],
    vector_field: [...first.vector_field],
    weights_get: [...first.weights_get],
    weights_post: [...first.weights_post],
    finetune: [...first.finetune],
  };
  for (const src of rest) {
    merged.tokenize.push(...src.tokenize);
    merged.trace.push(...src.trace);
    merged.vector_field.push(...src.vector_field);
    merged.weights_get.push(...src.weights_get);
    merged.weights_post.push(...src.weights_post);
    merged.finetune.push(...src.finetune);
  }
  return merged;
}

// --- numeric tolerances -------------------------------------------------------------

// Relative 1e-5 per the spec, with an absolute floor of 2e-6: the backend itself
// computes in float32, so entries whose magnitude is suppressed by cancellation
// (e.g. tiny mlp_out components) carry ~1e-7..1e-6 of the BACKEND's own roundoff
// that no float64 port can track relatively. All order-1 quantities (unit-sphere
// points, hidden states, attention rows, probabilities) are still held to 1e-5.
// Goldens additionally went through the contract's 6-significant-digit rounding
// (<=5e-7 relative), well inside this band.
export const RTOL = 1e-5;
export const ATOL = 2e-6;

export function expectClose(actual: number, golden: number, context: string): void {
  const tol = ATOL + RTOL * Math.max(Math.abs(actual), Math.abs(golden));
  if (!(Math.abs(actual - golden) <= tol)) {
    throw new Error(`${context}: |${actual} - ${golden}| = ${Math.abs(actual - golden)} > ${tol}`);
  }
}

export function expectVecClose(actual: number[], golden: number[], context: string): void {
  if (actual.length !== golden.length) {
    throw new Error(`${context}: length ${actual.length} != ${golden.length}`);
  }
  for (let i = 0; i < golden.length; i++) expectClose(actual[i], golden[i], `${context}[${i}]`);
}

export function expectMatrixClose(actual: number[][], golden: number[][], context: string): void {
  if (actual.length !== golden.length) {
    throw new Error(`${context}: rows ${actual.length} != ${golden.length}`);
  }
  for (let i = 0; i < golden.length; i++) expectVecClose(actual[i], golden[i], `${context}[${i}]`);
}
