/**
 * Shared golden-asset loading for the geoEngine test suites.
 *
 * Two independent real-backend golden sources exist:
 *   - public/static-data/geo/ — the static-site export (scripts/
 *     export_static_assets.py), schema {cases, weight_edits, finetune},
 *     normalized onto the fixture schema here; and
 *   - tests/fixtures/geo/ — committed fixtures generated by
 *     tests/fixtures/geo/generate.py (uvicorn + the backend's own geo
 *     functions — nothing hand-written), schema "geo-golden-v1".
 *
 * WHY sources are PAIRED (golden + checkpoint + vocab together), never merged:
 * each golden set is produced by a REAL training run, and training is
 * platform-sensitive at the bit level (BLAS kernels, op fusion, reduction
 * order). The committed fixtures were trained on macOS while CI regenerates
 * the static export on Linux, so the two checkpoints legitimately diverge
 * beyond test tolerances. A golden set is therefore only ever meaningful
 * against an engine built from ITS OWN source's checkpoint + vocab — which is
 * exactly what goldenSources() returns. The suites run once per source,
 * cross-validating both independent exporters against the TS engine.
 */

import fs from "node:fs";
import path from "node:path";

export const STATIC_DIR = path.resolve(__dirname, "../../public/static-data/geo");
export const FIXTURE_DIR = path.resolve(__dirname, "../fixtures/geo");

export function loadJson(file: string): unknown {
  return JSON.parse(fs.readFileSync(file, "utf-8"));
}

export interface GoldenFile {
  format: string;
  spec: Record<string, any>;
  tokenize: { text: string; response: Record<string, any> }[];
  trace: { prompt: string; response: Record<string, any> }[];
  vector_field: { params: Record<string, any>; response: Record<string, any> }[];
  weights_get: { params: Record<string, any>; response: Record<string, any> }[];
  weights_post: { body: Record<string, any>; response: Record<string, any> }[];
  finetune: { body: Record<string, any>; result: Record<string, any> }[];
}

/**
 * Normalize the static-site export's golden schema ({cases: [{prompt, trace,
 * fields: [{params, response}]}], weight_edits, finetune}) onto GoldenFile.
 * Field params there omit the prompt (it is the case's); weight_edits carry the
 * minted token but no `edited` summaries (assertions treat `edited` as
 * optional); the spec golden is the exported spec.json.
 */
function normalizeStaticGolden(data: any): GoldenFile | null {
  if (!Array.isArray(data?.cases) || !Array.isArray(data?.weight_edits)) return null;
  let spec: Record<string, any>;
  try {
    spec = loadJson(path.join(STATIC_DIR, "spec.json")) as Record<string, any>;
  } catch {
    return null;
  }
  const trace: GoldenFile["trace"] = [];
  const vector_field: GoldenFile["vector_field"] = [];
  for (const c of data.cases) {
    trace.push({ prompt: c.prompt, response: c.trace });
    for (const f of c.fields ?? []) {
      vector_field.push({ params: { ...f.params, prompt: c.prompt }, response: f.response });
    }
  }
  const weights_post: GoldenFile["weights_post"] = data.weight_edits.map((w: any) => ({
    body: w.body,
    response: { weights_token: w.weights_token },
  }));
  const finetune: GoldenFile["finetune"] = [];
  const ft = data.finetune;
  if (ft && typeof ft.text === "string") {
    finetune.push({
      body: { text: ft.text, steps: ft.steps, lr: ft.lr, seed: ft.seed },
      result: {
        weights_token: ft.weights_token,
        loss_before: ft.loss_before,
        loss_after: ft.loss_after,
      },
    });
  }
  return {
    format: "geo-golden-v1(normalized-static)",
    spec,
    tokenize: [], // no tokenize goldens in the static export; trace.tokens are id-exact instead
    trace,
    vector_field,
    weights_get: [],
    weights_post,
    finetune,
  };
}

/**
 * A golden set PAIRED with the checkpoint + vocab of the run that produced it.
 * See the file header: training is platform-divergent, so a golden set must
 * only be evaluated against an engine built from its own source's assets.
 */
export interface GoldenSource {
  name: "static-export" | "fixtures";
  golden: GoldenFile;
  checkpoint: unknown;
  vocab: unknown;
}

/**
 * All golden sources: the static-site export first (when golden.json,
 * checkpoint.json, and vocab.json ALL exist and parse under STATIC_DIR), then
 * the committed fixtures (always present; generate.py emits exactly
 * golden.json + checkpoint.json + vocab.json into FIXTURE_DIR).
 */
export function goldenSources(): GoldenSource[] {
  const sources: GoldenSource[] = [];
  const staticGolden = path.join(STATIC_DIR, "golden.json");
  const staticCheckpoint = path.join(STATIC_DIR, "checkpoint.json");
  const staticVocab = path.join(STATIC_DIR, "vocab.json");
  if ([staticGolden, staticCheckpoint, staticVocab].every((f) => fs.existsSync(f))) {
    try {
      const data = loadJson(staticGolden) as any;
      const golden =
        data?.format === "geo-golden-v1" && Array.isArray(data.trace)
          ? (data as GoldenFile)
          : normalizeStaticGolden(data);
      if (golden) {
        sources.push({
          name: "static-export",
          golden,
          checkpoint: loadJson(staticCheckpoint),
          vocab: loadJson(staticVocab),
        });
      } else {
        console.warn(
          "static-data/geo/golden.json has an unrecognized schema; skipping the static source",
        );
      }
    } catch (err) {
      console.warn("static-data/geo assets failed to parse; skipping the static source", err);
    }
  }
  sources.push({
    name: "fixtures",
    golden: loadJson(path.join(FIXTURE_DIR, "golden.json")) as GoldenFile,
    checkpoint: loadJson(path.join(FIXTURE_DIR, "checkpoint.json")),
    vocab: loadJson(path.join(FIXTURE_DIR, "vocab.json")),
  });
  return sources;
}

// --- numeric tolerances -------------------------------------------------------------

// Relative 1e-5 per the spec, with an absolute floor of 2e-6: the backend itself
// computes in float32, so entries whose magnitude is suppressed by cancellation
// (e.g. tiny mlp_out components) carry ~1e-7..1e-6 of the BACKEND's own roundoff
// that no float64 port can track relatively. All order-1 quantities (unit-sphere
// points, hidden states, attention rows, probabilities) are still held to 1e-5.
// Goldens additionally went through the contract's 6-significant-digit rounding
// (<=5e-7 relative), well inside this band.
export const RTOL = 1e-5;
export const ATOL = 2e-6;

export function expectClose(actual: number, golden: number, context: string): void {
  const tol = ATOL + RTOL * Math.max(Math.abs(actual), Math.abs(golden));
  if (!(Math.abs(actual - golden) <= tol)) {
    throw new Error(`${context}: |${actual} - ${golden}| = ${Math.abs(actual - golden)} > ${tol}`);
  }
}

export function expectVecClose(actual: number[], golden: number[], context: string): void {
  if (actual.length !== golden.length) {
    throw new Error(`${context}: length ${actual.length} != ${golden.length}`);
  }
  for (let i = 0; i < golden.length; i++) expectClose(actual[i], golden[i], `${context}[${i}]`);
}

export function expectMatrixClose(actual: number[][], golden: number[][], context: string): void {
  if (actual.length !== golden.length) {
    throw new Error(`${context}: rows ${actual.length} != ${golden.length}`);
  }
  for (let i = 0; i < golden.length; i++) expectVecClose(actual[i], golden[i], `${context}[${i}]`);
}
