/**
 * Cross-language golden for ONE from-scratch training step.
 *
 * `scratch.ts` used to claim, in a comment, that "the golden test pins one
 * forward+backward step from a FIXED initialization rather than a whole run". No such
 * test existed: the Adam update and the Wang & Isola uniformity gradient — the two
 * pieces of arithmetic that fine-tuning does NOT exercise — had zero cross-language
 * coverage in either direction. This is that test, for real.
 *
 * Why it has to be one step rather than a run: numpy/torch's RNG streams cannot be
 * reproduced in JS, so two runs "from the same seed" are two different runs (measured:
 * max|PY−TS| embedding 1.93 on unit vectors — near-antipodal — with final losses
 * agreeing to 0.0015, which is exactly why loss comparison could never have caught a
 * port bug here). Making the initialization and the repulsion sample indices DATA
 * instead of RNG output removes the obstacle entirely: both stacks run the identical
 * step on the identical inputs.
 *
 * The fixture is produced by the real Python backend — `tests/fixtures/geo/generate.py`
 * calls `llm_geometry.geo.train.train_batch_step`, the very function `train_geo_model`
 * uses for every batch of a real run. Nothing here is hand-authored.
 */

import fs from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { makeWindows } from "../../src/lib/geoEngine/finetune";
import { CONTEXT_WINDOW, EOS_ID, GeoModel, type WeightSet } from "../../src/lib/geoEngine/model";
import { newAdamState, scratchTrainStep } from "../../src/lib/geoEngine/scratch";
import { FIXTURE_DIR, loadJson } from "./geoGoldenAssets";

interface ScratchStepGolden {
  format: string;
  params: { lr: number; repulsion_weight: number; batch_size: number; stride: number };
  token_ids: number[];
  sample_idx: number[];
  ce: number;
  uniformity: number;
  grad_norm: number;
  grads: Record<string, string>;
  weights_after: Record<string, string>;
}

function f32FromB64(b64: string): Float32Array {
  const bytes = Buffer.from(b64, "base64");
  return new Float32Array(bytes.buffer, bytes.byteOffset, bytes.byteLength / 4);
}

/** The canonical weight set, from the same fixture run that produced the golden. */
function fixtureWeights(): WeightSet {
  const checkpoint = loadJson(path.join(FIXTURE_DIR, "checkpoint.json")) as {
    state_dict: Record<string, number[] | number[][]>;
  };
  const ws: WeightSet = {};
  for (const [name, nested] of Object.entries(checkpoint.state_dict)) {
    const flat = (nested as unknown[]).flat(2) as number[];
    ws[name] = Float32Array.from(flat);
  }
  return ws;
}

const goldenPath = path.join(FIXTURE_DIR, "scratch_step.json");

describe("from-scratch training step vs the Python backend [fixtures]", () => {
  it("has a committed golden generated by the real backend", () => {
    expect(fs.existsSync(goldenPath), `${goldenPath} is missing — run generate.py`).toBe(true);
    const golden = loadJson(goldenPath) as ScratchStepGolden;
    expect(golden.format).toBe("geo-scratch-step-v1");
    expect(golden.sample_idx.length).toBe(256);
    expect(golden.token_ids.length).toBeGreaterThan(CONTEXT_WINDOW);
  });

  it("reproduces the losses, the gradients and the post-step weights", () => {
    const golden = loadJson(goldenPath) as ScratchStepGolden;
    const ws = fixtureWeights();
    const model = new GeoModel(ws);
    const { adam, grads } = newAdamState(ws);
    const windows = makeWindows(
      [...golden.token_ids, EOS_ID],
      CONTEXT_WINDOW,
      golden.params.stride,
    ).slice(0, golden.params.batch_size);
    expect(windows.length).toBe(golden.params.batch_size);

    const result = scratchTrainStep(
      model,
      ws,
      adam,
      grads,
      windows,
      Int32Array.from(golden.sample_idx),
      golden.params.lr,
      golden.params.repulsion_weight,
    );

    // Losses: pure float arithmetic over the same numbers, so tight.
    expect(Math.abs(result.ce - golden.ce) / Math.abs(golden.ce)).toBeLessThan(1e-5);
    expect(Math.abs(result.uniformity - golden.uniformity) / Math.abs(golden.uniformity)).toBeLessThan(1e-5);

    // The GRADIENTS are the real cross-language quantity: the uniformity gradient is
    // hand-derived in TS (torch autodiffs it), so this is the only thing that can
    // catch a sign or factor error in it. Compared per tensor, relative to that
    // tensor's own scale — an absolute bound would be meaningless across tensors
    // whose gradients differ by orders of magnitude.
    for (const [name, b64] of Object.entries(golden.grads)) {
      const want = f32FromB64(b64);
      const got = grads[name];
      expect(got, name).toBeDefined();
      expect(got.length, name).toBe(want.length);
      let maxAbsDiff = 0;
      let scale = 0;
      for (let i = 0; i < want.length; i++) {
        maxAbsDiff = Math.max(maxAbsDiff, Math.abs(got[i] - want[i]));
        scale = Math.max(scale, Math.abs(want[i]));
      }
      // float32 torch grads vs float64 JS accumulation over a 64×50×1003 softmax.
      expect(maxAbsDiff, `${name}: max|TS-PY| ${maxAbsDiff} (scale ${scale})`).toBeLessThan(
        1e-5 * Math.max(scale, 1e-3),
      );
    }

    // And the weights the step actually produced, including the S² re-projection.
    for (const [name, b64] of Object.entries(golden.weights_after)) {
      const want = f32FromB64(b64);
      const got = ws[name];
      let maxAbsDiff = 0;
      for (let i = 0; i < want.length; i++) maxAbsDiff = Math.max(maxAbsDiff, Math.abs(got[i] - want[i]));
      expect(maxAbsDiff, `${name}: max|TS-PY| after the step`).toBeLessThan(1e-5);
    }

    // Adam bookkeeping advanced exactly once, and the pre-clip gradient norm agrees
    // (it is what decides whether the clip fires at all).
    expect(adam.t).toBe(1);
    expect(Math.abs(result.gradNorm - golden.grad_norm) / golden.grad_norm).toBeLessThan(1e-5);
  });
});
