/**
 * The Lexicon Lab browser engine, tested against real computation only.
 *
 * No mocks and no fixtures of convenience. In particular:
 *
 *   * the Dolch lists are compared WORD FOR WORD against the Python module that is the
 *     source of truth (`lex/dolch.py`), parsed out of the file itself — so "the TS
 *     mirrors Python" is measured, not asserted;
 *   * the Jacobi eigensolver is checked against eigenvalues computed by numpy/LAPACK
 *     (`numpy.linalg.eigvalsh`) for symmetric integer matrices generated by a Lehmer LCG
 *     that is exactly reproducible in both languages — every intermediate is an integer
 *     below 2^53, so the two languages see byte-identical inputs;
 *   * training really trains, on the real committed corpus, and the loss is measured
 *     before and after;
 *   * generation is checked for out-of-budget words at every Dolch budget size.
 */

import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import {
  DOLCH_ORDER,
  FIRST,
  NOUNS,
  PRE_PRIMER,
  PRIMER,
  SECOND,
  THIRD,
  dolchBudget,
  dolchSizes,
} from "../../src/lib/lexEngine/dolch";
import {
  GENERATION_BANNED_IDS,
  LexVocab,
  SPECIAL_TOKENS,
  buildVocab,
  frequencyBudget,
  tokenize,
} from "../../src/lib/lexEngine/vocab";
import {
  LexModel,
  backward,
  crossEntropy,
  decayedWeightNames,
  defaultConfig,
  initWeights,
  paramCount,
  sfc32,
  weightNames,
  zeroGrads,
} from "../../src/lib/lexEngine/model";
import {
  centreColumns,
  gram,
  jacobiEigen,
  randomBaselineSpectrum,
  spectrum,
  spectrumStats,
} from "../../src/lib/lexEngine/spectrum";
import {
  evalLoss,
  oneCycleLr,
  pyRound,
  runTraining,
  sampleBatch,
  splitTokens,
  tokenStream,
} from "../../src/lib/lexEngine/train";
import { generate } from "../../src/lib/lexEngine/generate";
import { runTrainingJob, type LexTrainResponse } from "../../src/lib/lexEngine/trainWorker";
import { modelOf, trainInWorker, vocabOf, type TrainProgress } from "../../src/lib/lexEngine";

const PY_DOLCH = path.resolve(__dirname, "../../../backend/src/llm_geometry/lex/dolch.py");
const PY_VOCAB = path.resolve(__dirname, "../../../backend/src/llm_geometry/lex/vocab.py");
const CORPUS = path.resolve(__dirname, "../../../backend/src/llm_geometry/lex/data/real-mother-goose.txt");

// --- the Python source of truth ------------------------------------------------------

/** Extract a `NAME = """..."""` .split() block from the Python module, verbatim. */
function pythonWordList(source: string, name: string): string[] {
  const m = new RegExp(`^${name} = """([\\s\\S]*?)"""\\.split\\(\\)`, "m").exec(source);
  if (!m) throw new Error(`could not find the Python list ${name} — has lex/dolch.py been restructured?`);
  return m[1].split(/\s+/).filter((w) => w.length > 0);
}

const pySource = fs.readFileSync(PY_DOLCH, "utf-8");

/** The Gutenberg body, trimmed the way `lex/corpus.py` trims it before use. */
function corpusBody(raw: string): string {
  const lines = raw.split(/\r?\n/);
  let start = 0;
  let end = lines.length;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].includes("*** START OF THE PROJECT GUTENBERG")) start = i + 1;
    else if (lines[i].includes("*** END OF THE PROJECT GUTENBERG")) {
      end = i;
      break;
    }
  }
  return lines.slice(start, end).join("\n").replace(/^\n+|\n+$/g, "");
}

const corpusText = corpusBody(fs.readFileSync(CORPUS, "utf-8"));

// --- Dolch ---------------------------------------------------------------------------

describe("Dolch lists", () => {
  it("transcribes lex/dolch.py word for word", () => {
    const pairs: [string, string[]][] = [
      ["PRE_PRIMER", PRE_PRIMER],
      ["PRIMER", PRIMER],
      ["FIRST", FIRST],
      ["SECOND", SECOND],
      ["THIRD", THIRD],
      ["NOUNS", NOUNS],
    ];
    for (const [name, ts] of pairs) {
      expect(ts, `${name} differs from Python`).toEqual(pythonWordList(pySource, name));
    }
  });

  it("keeps both corrections: first grade has `going`, not `giving`", () => {
    expect(FIRST).toContain("going");
    expect(FIRST).not.toContain("giving");
    // `give` is separately present, which is why `giving` was a slip and not a variant.
    expect(FIRST).toContain("give");
    for (const name of DOLCH_ORDER) expect(dolchBudget(name)).not.toContain("giving");
  });

  it("drops `Santa Claus`: no budget entry contains a space", () => {
    for (const name of DOLCH_ORDER) {
      for (const w of dolchBudget(name)) expect(w).not.toMatch(/\s/);
    }
    expect(NOUNS).not.toContain("Santa");
    expect(NOUNS).not.toContain("Claus");
    expect(dolchBudget("full")).not.toContain("santa claus");
  });

  it("measures the budget sizes 40/92/133/220/314", () => {
    expect(dolchSizes()).toEqual({ pre_primer: 40, primer: 92, first: 133, service: 220, full: 314 });
  });

  it("nests each budget in the next", () => {
    for (let i = 1; i < DOLCH_ORDER.length; i++) {
      const smaller = dolchBudget(DOLCH_ORDER[i - 1]);
      const larger = new Set(dolchBudget(DOLCH_ORDER[i]));
      for (const w of smaller) expect(larger.has(w)).toBe(true);
    }
  });
});

// --- tokenizer and budgets -----------------------------------------------------------

describe("tokenizer", () => {
  it("uses the same pattern source as Python", () => {
    const py = /WORD_RE = re\.compile\(r"([^"]+)"\)/.exec(fs.readFileSync(PY_VOCAB, "utf-8"));
    expect(py, "lex/vocab.py no longer declares WORD_RE the expected way").not.toBeNull();
    expect((py as RegExpExecArray)[1]).toBe("[A-Za-z]+(?:['\\-][A-Za-z]+)*");
  });

  it("keeps `don't` and `good-bye` as single tokens", () => {
    expect(tokenize("Don't say good-bye!")).toEqual(["don't", "say", "good-bye"]);
    // Both are real Dolch entries, so they must survive to be reachable at all.
    expect(dolchBudget("full")).toContain("don't");
    expect(dolchBudget("full")).toContain("good-bye");
  });

  it("drops punctuation and digits rather than tokenizing them", () => {
    expect(tokenize("Hey, diddle 42 diddle -- the cat!")).toEqual(["hey", "diddle", "diddle", "the", "cat"]);
    // A trailing apostrophe is not part of the word: the group needs letters after it.
    expect(tokenize("cats' -hat- 'tis")).toEqual(["cats", "hat", "tis"]);
  });

  it("breaks frequency ties alphabetically", () => {
    // "b", "c" and "a" all occur twice; "z" occurs three times.
    const text = "z z z c c b b a a";
    expect(frequencyBudget(text, 4)).toEqual(["z", "a", "b", "c"]);
  });
});

describe("budgets", () => {
  it("lays out specials first and reports |V| separately from the rows", () => {
    const vocab = buildVocab("dolch", "full", corpusText);
    expect(vocab.budgetSize).toBe(314);
    expect(vocab.rows).toBe(318);
    expect(vocab.itos.slice(0, 4)).toEqual([...SPECIAL_TOKENS]);
    expect(vocab.stoi("<unk>")).toBe(0);
    expect(vocab.stoi("a-word-no-budget-has")).toBe(0); // out of budget -> <unk>
  });

  it("offers a frequency budget at the matched |V|, and it differs from Dolch", () => {
    const dolch = buildVocab("dolch", "full", corpusText);
    const freq = buildVocab("frequency", "full", corpusText);
    expect(freq.budgetSize).toBe(dolch.budgetSize);
    expect(freq.budgetName).toBe("top314");
    expect(new Set(freq.words)).not.toEqual(new Set(dolch.words));

    // SC-603: switching source at matched |V| measurably changes coverage.
    const a = dolch.coverage(corpusText);
    const b = freq.coverage(corpusText);
    expect(a.total_tokens).toBe(b.total_tokens);
    expect(b.token_coverage).not.toBeCloseTo(a.token_coverage, 6);
    expect(a.token_coverage + a.unk_rate).toBeCloseTo(1, 12);
    expect(a.whole_lines_in_budget).toBeLessThanOrEqual(a.total_lines);
  });
});

// --- the eigensolver -----------------------------------------------------------------

/**
 * Lehmer (MINSTD) LCG. Every product stays below 2^53, so JS doubles and Python ints
 * agree exactly and the generated matrices are identical in both languages.
 */
function lehmer(seed: number): () => number {
  let x = seed;
  return () => {
    x = (16807 * x) % 2147483647;
    return x;
  };
}

function symmetricInts(n: number, seed: number): Float64Array {
  const next = lehmer(seed);
  const M = new Float64Array(n * n);
  for (let i = 0; i < n; i++) {
    for (let j = i; j < n; j++) {
      const v = (next() % 21) - 10;
      M[i * n + j] = v;
      M[j * n + i] = v;
    }
  }
  return M;
}

/**
 * Golden eigenvalues from numpy.linalg.eigvalsh (LAPACK dsyevd), descending, for the
 * matrices `symmetricInts` generates. Regenerate with, from code/backend:
 *
 *   .venv/bin/python -c "...numpy.linalg.eigvalsh(sym(n, seed))[::-1]..."
 */
const GOLDEN_EIGENVALUES: Record<string, number[]> = {
  "5:12345": [16.322244970400007, 5.953959049079224, -0.827187275849658, -9.441130740245933, -20.007886003383625],
  "10:777": [
    30.90124709462677, 29.118840296155014, 19.04010134303768, 13.344906322831255, 1.479623162256573,
    -0.8565563146287202, -7.346519707243136, -10.530858122613953, -20.818349560276488, -26.33243451414499,
  ],
  "16:99": [
    36.595875437838814, 30.357018457418487, 19.890600921371636, 19.316819427266733, 16.30815177164707,
    13.190407779688282, 4.7998186328933015, 1.2140702919344561, -2.3947400348136694, -5.193223884372126,
    -7.34843313274854, -16.247194841928614, -17.916948777142903, -26.783035515863002, -46.28880772691947,
    -47.50037880627042,
  ],
};

describe("Jacobi eigendecomposition", () => {
  it("agrees with numpy/LAPACK on random symmetric matrices to 1e-9", () => {
    for (const [key, golden] of Object.entries(GOLDEN_EIGENVALUES)) {
      const [nStr, seedStr] = key.split(":");
      const n = Number(nStr);
      const M = symmetricInts(n, Number(seedStr));
      const { values } = jacobiEigen(M, n);
      expect(values.length).toBe(golden.length);
      for (let i = 0; i < n; i++) {
        expect(Math.abs(values[i] - golden[i]), `${key} eigenvalue ${i}`).toBeLessThan(1e-9);
      }
    }
  });

  it("returns orthonormal eigenvectors that reconstruct the matrix", () => {
    const n = 16;
    const M = symmetricInts(n, 99);
    const { values, vectors } = jacobiEigen(M, n);
    // V^T V = I
    for (let i = 0; i < n; i++) {
      for (let j = 0; j < n; j++) {
        let s = 0;
        for (let k = 0; k < n; k++) s += vectors[k * n + i] * vectors[k * n + j];
        expect(Math.abs(s - (i === j ? 1 : 0))).toBeLessThan(1e-12);
      }
    }
    // V diag(lambda) V^T = M
    let worst = 0;
    for (let i = 0; i < n; i++) {
      for (let j = 0; j < n; j++) {
        let s = 0;
        for (let k = 0; k < n; k++) s += vectors[i * n + k] * values[k] * vectors[j * n + k];
        worst = Math.max(worst, Math.abs(s - M[i * n + j]));
      }
    }
    expect(worst).toBeLessThan(1e-12);
  });

  it("handles the degenerate cases a real embedding can hit", () => {
    expect(Array.from(jacobiEigen([4], 1).values)).toEqual([4]);
    const zero = jacobiEigen(new Float64Array(9), 3);
    expect(Array.from(zero.values)).toEqual([0, 0, 0]);
    // A multiple of the identity: every eigenvalue equal, eigenvectors still orthonormal.
    const I3 = Float64Array.from([2, 0, 0, 0, 2, 0, 0, 0, 2]);
    expect(Array.from(jacobiEigen(I3, 3).values)).toEqual([2, 2, 2]);
  });
});

// --- the spectrum --------------------------------------------------------------------

/** Column-mean-zero ORTHONORMAL columns: centring is a no-op, so the Gram is exactly I. */
function orthonormalMeanZero(rows: number, cols: number, seed: number): Float64Array {
  const next = lehmer(seed);
  const A = centreColumns(
    Float64Array.from({ length: rows * cols }, () => (next() % 2001) / 1000 - 1),
    rows,
    cols,
  );
  // Modified Gram-Schmidt. Column-mean-zero is a linear subspace, so it is preserved.
  for (let j = 0; j < cols; j++) {
    for (let k = 0; k < j; k++) {
      let dot = 0;
      for (let r = 0; r < rows; r++) dot += A[r * cols + j] * A[r * cols + k];
      for (let r = 0; r < rows; r++) A[r * cols + j] -= dot * A[r * cols + k];
    }
    let norm = 0;
    for (let r = 0; r < rows; r++) norm += A[r * cols + j] * A[r * cols + j];
    norm = Math.sqrt(norm);
    for (let r = 0; r < rows; r++) A[r * cols + j] /= norm;
  }
  return A;
}

describe("spectrum", () => {
  it("gives orthonormal columns an effective rank of exactly d", () => {
    for (const d of [4, 16, 32]) {
      const rows = 200;
      const A = orthonormalMeanZero(rows, d, 4242 + d);
      const G = gram(centreColumns(A, rows, d), rows, d);
      // Sanity: the Gram really is the identity, so this is a clean d-fold degeneracy.
      for (let i = 0; i < d; i++) {
        for (let j = 0; j < d; j++) {
          expect(Math.abs(G[i * d + j] - (i === j ? 1 : 0))).toBeLessThan(1e-10);
        }
      }
      const s = spectrum(A, rows, d);
      expect(Math.abs(s.effectiveRank - d)).toBeLessThan(1e-8);
      expect(Math.abs(s.stableRank - d)).toBeLessThan(1e-8);
      expect(Math.abs(s.participationRatio - d)).toBeLessThan(1e-8);
      expect(s.ceiling).toBe(Math.min(rows - 1, d));
    }
  });

  it("gives a rank-1 matrix an effective rank of exactly 1", () => {
    const rows = 50;
    const cols = 8;
    const A = new Float64Array(rows * cols);
    const u = Float64Array.from({ length: rows }, (_, i) => Math.sin(i) + 2);
    const v = Float64Array.from({ length: cols }, (_, j) => j + 1);
    for (let r = 0; r < rows; r++) for (let c = 0; c < cols; c++) A[r * cols + c] = u[r] * v[c];
    const s = spectrum(A, rows, cols);
    expect(Math.abs(s.effectiveRank - 1)).toBeLessThan(1e-9);
    expect(Math.abs(s.stableRank - 1)).toBeLessThan(1e-9);
    expect(Math.abs(s.participationRatio - 1)).toBeLessThan(1e-9);
    expect(s.nDimsFor90pct).toBe(1);
    expect(s.fracVarTop2).toBeCloseTo(1, 9);
    // Every trailing eigenvalue is clamped to zero, never negative.
    for (const l of s.eigenvalues) expect(l).toBeGreaterThanOrEqual(0);
  });

  it("returns zeroes rather than NaN for a constant matrix", () => {
    const A = new Float64Array(20 * 4).fill(7);
    const s = spectrum(A, 20, 4);
    expect(s.totalVariance).toBe(0);
    expect(s.effectiveRank).toBe(0);
    expect(s.explainedVarianceRatio).toEqual([0, 0, 0]);
  });

  it("reproduces the Python random-init effective ranks, and does NOT plateau at the ceiling", () => {
    // FR-622 / SC-604. Effective rank is an ENTROPY, not a count: the algebraic rank
    // saturates min(|V|-1, d) = 128 from the `first` budget onward, while effective rank
    // is still climbing (with decelerating increments) at |V| = 314.
    //
    // The reference numbers are the real Python implementation's, random-init at
    // d_model=128. TS and Python draw INDEPENDENT samples from the same N(0, 0.02^2) —
    // portable RNG equality is not claimed anywhere in this feature — so the check is a
    // tolerance, sized from the observed spread across seeds (~1.1 at its widest).
    const reference: [number, number, number][] = [
      // rows, ceiling, python effective rank
      [44, 43, 36.208],
      [96, 95, 64.384],
      [137, 128, 79.113],
      [224, 128, 95.732],
      [318, 128, 104.155],
    ];
    const measured: number[] = [];
    for (const [rows, ceiling, expected] of reference) {
      const s = randomBaselineSpectrum(rows, 128, 0);
      expect(s.ceiling, `ceiling at rows=${rows}`).toBe(ceiling);
      expect(Math.abs(s.effectiveRank - expected), `effective rank at rows=${rows}`).toBeLessThan(1.5);
      expect(s.effectiveRank).toBeLessThan(s.ceiling);
      measured.push(s.effectiveRank);
    }
    // Still climbing at the largest budget, and strictly so at every step.
    for (let i = 1; i < measured.length; i++) expect(measured[i]).toBeGreaterThan(measured[i - 1]);
    // ... but far from the ceiling it would only reach with a perfectly flat spectrum.
    expect(measured[measured.length - 1]).toBeLessThan(0.85 * 128);
    // The increments decelerate, which is what "not a plateau at the ceiling" looks like.
    expect(measured[4] - measured[3]).toBeLessThan(measured[1] - measured[0]);
  });

  it("canonicalizes eigenvector signs so two correct runs cannot mirror each other", () => {
    const n = 10;
    const M = symmetricInts(n, 777);
    const { vectors } = jacobiEigen(M, n);
    for (let j = 0; j < n; j++) {
      let best = 0;
      let bestAbs = -1;
      for (let i = 0; i < n; i++) {
        const m = Math.abs(vectors[i * n + j]);
        if (m > bestAbs) {
          bestAbs = m;
          best = i;
        }
      }
      expect(vectors[best * n + j], `column ${j}'s largest entry must be positive`).toBeGreaterThan(0);
    }
    // Negating the input's eigenbasis must not change the PCA coordinates' orientation:
    // the same matrix scaled by a positive factor gives proportional, not mirrored, coords.
    const rows = 40;
    const cols = 6;
    const next = lehmer(21);
    const A = Float64Array.from({ length: rows * cols }, () => (next() % 500) / 100 - 2.5);
    const a = spectrum(A, rows, cols);
    const scaled = Float64Array.from(A, (x) => 3 * x);
    const b = spectrum(scaled, rows, cols);
    for (let i = 0; i < rows * 3; i++) expect(b.coords[i]).toBeCloseTo(3 * a.coords[i], 9);
  });

  it("projects onto the top components with a matching explained variance", () => {
    const rows = 120;
    const cols = 10;
    const next = lehmer(31);
    const A = Float64Array.from({ length: rows * cols }, () => (next() % 1000) / 250 - 2);
    const s = spectrum(A, rows, cols);
    expect(s.coords.length).toBe(rows * 3);
    // Variance of PCA component j equals lambda_j (the coordinates are already centred).
    for (let j = 0; j < 3; j++) {
      let ss = 0;
      for (let r = 0; r < rows; r++) ss += s.coords[r * 3 + j] * s.coords[r * 3 + j];
      expect(Math.abs(ss - s.eigenvalues[j]) / s.eigenvalues[j]).toBeLessThan(1e-9);
    }
    const sumRatio = s.explainedVarianceRatio.reduce((a, b) => a + b, 0);
    expect(sumRatio).toBeGreaterThan(0);
    expect(sumRatio).toBeLessThanOrEqual(1 + 1e-12);
    expect(s.fracVarTop2).toBeCloseTo(s.explainedVarianceRatio[0] + s.explainedVarianceRatio[1], 12);
  });

  it("agrees with a direct Gram computation, since that is all it is", () => {
    const rows = 30;
    const cols = 6;
    const next = lehmer(5);
    const A = Float64Array.from({ length: rows * cols }, () => (next() % 100) / 10);
    const direct = spectrumStats(jacobiEigen(gram(centreColumns(A, rows, cols), rows, cols), cols).values, rows, cols);
    const viaSpectrum = spectrum(A, rows, cols);
    expect(viaSpectrum.effectiveRank).toBeCloseTo(direct.effectiveRank, 12);
    expect(viaSpectrum.singularValues[0]).toBeCloseTo(direct.singularValues[0], 12);
  });
});

// --- the model -----------------------------------------------------------------------

describe("model", () => {
  it("allocates exactly paramCount() scalars, tied and untied", () => {
    const configs = [
      { vocabRows: 44, dModel: 16, nLayers: 1, nHeads: 1, ctx: 32, tied: true },
      { vocabRows: 96, dModel: 32, nLayers: 2, nHeads: 2, ctx: 64, tied: true },
      { vocabRows: 137, dModel: 64, nLayers: 3, nHeads: 4, ctx: 128, tied: false },
      { vocabRows: 318, dModel: 64, nLayers: 2, nHeads: 2, ctx: 64, tied: true },
      { vocabRows: 318, dModel: 128, nLayers: 4, nHeads: 4, ctx: 128, tied: false },
    ];
    for (const c of configs) {
      const cfg = { ...c, dropout: 0 };
      const model = LexModel.fresh(cfg, 1);
      const expected = paramCount(c.vocabRows, c.dModel, c.nLayers, c.ctx, c.tied);
      expect(model.nParams, JSON.stringify(c)).toBe(expected);
      // The formula, spelled out per term, so a typo in either form is caught.
      const d = c.dModel;
      const manual =
        (c.tied ? 1 : 2) * c.vocabRows * d + c.ctx * d + c.nLayers * (12 * d * d + 13 * d) + 2 * d;
      expect(expected).toBe(manual);
    }
  });

  it("ties the readout to the embedding when asked, and not otherwise", () => {
    const rows = 24;
    const tied = LexModel.fresh({ vocabRows: rows, dModel: 8, nLayers: 1, nHeads: 2, ctx: 16, tied: true, dropout: 0 }, 3);
    expect(tied.headWeight).toBe(tied.weights.embed);
    expect(weightNames(tied.cfg)).not.toContain("head_w");

    const untied = LexModel.fresh({ vocabRows: rows, dModel: 8, nLayers: 1, nHeads: 2, ctx: 16, tied: false, dropout: 0 }, 3);
    expect(untied.headWeight).not.toBe(untied.weights.embed);
    expect(decayedWeightNames(untied.cfg)).toContain("head_w");
    expect(decayedWeightNames(tied.cfg)).not.toContain("head_w");
  });

  it("decays only the 2-D weight matrices (FR-614)", () => {
    const cfg = defaultConfig(40, { dModel: 16, nLayers: 2, nHeads: 2, ctx: 32, tied: false });
    const decayed = new Set(decayedWeightNames(cfg));
    expect(decayed).toEqual(
      new Set([
        "layers.0.qkv_w",
        "layers.0.proj_w",
        "layers.0.fc1_w",
        "layers.0.fc2_w",
        "layers.1.qkv_w",
        "layers.1.proj_w",
        "layers.1.fc1_w",
        "layers.1.fc2_w",
        "head_w",
      ]),
    );
    for (const name of ["embed", "pos", "lnf_g", "lnf_b", "layers.0.ln1_g", "layers.0.qkv_b"]) {
      expect(decayed.has(name)).toBe(false);
    }
  });

  it("initializes qkv_w xavier-uniform and everything else N(0, 0.02^2)", () => {
    const d = 128;
    const cfg = defaultConfig(318, { dModel: d, nLayers: 1, nHeads: 4, ctx: 64 });
    const ws = initWeights(cfg, 11);
    const std = (a: Float32Array): number => {
      let m = 0;
      for (const x of a) m += x;
      m /= a.length;
      let v = 0;
      for (const x of a) v += (x - m) * (x - m);
      return Math.sqrt(v / a.length);
    };
    const bound = Math.sqrt(6 / (3 * d + d));
    expect(bound).toBeCloseTo(0.10825, 5); // the value measured on the source at d=128
    let max = 0;
    for (const x of ws["layers.0.qkv_w"]) max = Math.max(max, Math.abs(x));
    expect(max).toBeLessThanOrEqual(bound);
    expect(max).toBeGreaterThan(0.99 * bound);
    expect(std(ws["layers.0.qkv_w"])).toBeCloseTo(bound / Math.sqrt(3), 3); // uniform std

    expect(std(ws.embed)).toBeCloseTo(0.02, 3);
    expect(std(ws["layers.0.fc1_w"])).toBeCloseTo(0.02, 3);
    expect(Array.from(ws["layers.0.ln1_g"].slice(0, 4))).toEqual([1, 1, 1, 1]);
    expect(Array.from(ws["layers.0.ln1_b"].slice(0, 4))).toEqual([0, 0, 0, 0]);
    expect(Array.from(ws.lnf_g.slice(0, 4))).toEqual([1, 1, 1, 1]);
  });

  it("is causal: a later token cannot change an earlier position's logits", () => {
    const cfg = defaultConfig(20, { dModel: 16, nLayers: 2, nHeads: 2, ctx: 8 });
    const model = LexModel.fresh(cfg, 5);
    const a = model.forward(Int32Array.from([4, 5, 6, 7]), 1, 4, {});
    const b = model.forward(Int32Array.from([4, 5, 6, 19]), 1, 4, {});
    const V = cfg.vocabRows;
    for (let t = 0; t < 3; t++) {
      for (let w = 0; w < V; w++) {
        expect(Math.abs(a.logits[t * V + w] - b.logits[t * V + w])).toBeLessThan(1e-12);
      }
    }
    // ...and the last position DOES change, or the test would prove nothing.
    let diff = 0;
    for (let w = 0; w < V; w++) diff += Math.abs(a.logits[3 * V + w] - b.logits[3 * V + w]);
    expect(diff).toBeGreaterThan(1e-6);
  });

  it("matches finite-difference gradients through the whole model", () => {
    // The real check on the hand-derived backward pass: every parameter family, tied and
    // untied, against a central difference of the actual loss.
    for (const tied of [true, false]) {
      const cfg = { vocabRows: 11, dModel: 8, nLayers: 2, nHeads: 2, ctx: 6, tied, dropout: 0 };
      const model = LexModel.fresh(cfg, 17);
      const ids = Int32Array.from([5, 2, 8, 4, 7, 6, 3, 9, 5, 10, 4, 8]);
      const targets = Int32Array.from([2, 8, 4, 7, 6, 1, 9, 5, 10, 4, 8, 7]);
      const B = 2;
      const T = 6;
      const N = B * T;
      const V = cfg.vocabRows;

      const lossOf = (): number => {
        const acts = model.forward(ids, B, T, {});
        const { ceSum, nValid } = crossEntropy(acts.logits, targets, N, V);
        return ceSum / nValid;
      };

      const grads = zeroGrads(cfg);
      const acts = model.forward(ids, B, T, {});
      const { dLogits } = crossEntropy(acts.logits, targets, N, V);
      backward(model, acts, dLogits, grads);

      const eps = 1e-3; // float32 weights: smaller steps drown in representation error
      for (const name of weightNames(cfg)) {
        const w = model.weights[name];
        for (const i of [0, Math.floor(w.length / 3), w.length - 1]) {
          const original = w[i];
          w[i] = Math.fround(original + eps);
          const up = lossOf();
          w[i] = Math.fround(original - eps);
          const down = lossOf();
          w[i] = original;
          const numeric = (up - down) / (Math.fround(original + eps) - Math.fround(original - eps));
          const analytic = grads[name][i];
          const scale = Math.max(1e-4, Math.abs(numeric), Math.abs(analytic));
          expect(Math.abs(numeric - analytic) / scale, `${name}[${i}] tied=${tied}`).toBeLessThan(2e-3);
        }
      }
    }
  });

  it("applies dropout only in training mode, and reproducibly", () => {
    const cfg = defaultConfig(20, { dModel: 16, nLayers: 1, nHeads: 2, ctx: 8, dropout: 0.3 });
    const model = LexModel.fresh(cfg, 2);
    const ids = Int32Array.from([4, 5, 6, 7]);
    const clean = model.forward(ids, 1, 4, {});
    const cleanAgain = model.forward(ids, 1, 4, {});
    expect(Array.from(clean.logits)).toEqual(Array.from(cleanAgain.logits));

    const dropped = model.forward(ids, 1, 4, { dropout: 0.3, rand: sfc32(9) });
    const droppedAgain = model.forward(ids, 1, 4, { dropout: 0.3, rand: sfc32(9) });
    expect(Array.from(dropped.logits)).toEqual(Array.from(droppedAgain.logits));
    expect(Array.from(dropped.logits)).not.toEqual(Array.from(clean.logits));
  });
});

// --- the training token stream -------------------------------------------------------

/**
 * The stream is a CONTRACT (`architecture.md` § Training, "Token stream construction"),
 * not an implementation detail: the browser used to train on `vocab.encodeText`, a flat
 * tokenize with no `<eos>` at all, so it never saw a line boundary, could not learn
 * verse, and reported 16,000 tokens where Python reported 19,071 — while the UI said
 * both runtimes ran the same recipe. These numbers come from running the real Python:
 *
 *   $ code/backend/.venv/bin/python -c "
 *     from llm_geometry.lex.corpus import load_corpus_text
 *     from llm_geometry.lex.vocab import build_vocab
 *     from llm_geometry.lex.train import token_stream
 *     body = load_corpus_text(); v = build_vocab('dolch', 'full', body)
 *     s = token_stream(body, v); print(len(s), int((s == 2).sum()))"
 *   19071 3071
 */
describe("the training token stream", () => {
  it("matches Python's token_stream element for element on a multi-line fixture", () => {
    // Exercises every rule at once: a `\r\n` break, an empty line, a whitespace-only
    // line, a punctuation-only line (no word token — emits NOTHING, not a bare `<eos>`),
    // out-of-budget words as `<unk>`, an apostrophe and a hyphen token, and a final line
    // with no trailing newline (which still gets its `<eos>`).
    const FIXTURE =
      "Jack and Jill went up the hill\r\n" +
      "\n" +
      "   \n" +
      "-- ... --\n" +
      "To fetch a pail of water; don't stop!\n" +
      "Good-bye, Humpty Dumpty\n" +
      "trailing no newline";
    // Printed by `token_stream(FIXTURE, build_vocab("dolch", "full", ""))` in the backend venv.
    const PY_IDS = [0, 5, 0, 89, 39, 35, 271, 2, 37, 0, 4, 0, 120, 313, 148, 128, 2, 266, 0, 0, 2, 0, 66, 0, 2];
    const vocab = buildVocab("dolch", "full", "");
    expect(tokenStream(FIXTURE, vocab)).toEqual(PY_IDS);
    expect(vocab.decode(tokenStream(FIXTURE, vocab))).toEqual([
      "<unk>", "and", "<unk>", "went", "up", "the", "hill", "<eos>",
      "to", "<unk>", "a", "<unk>", "of", "water", "don't", "stop", "<eos>",
      "good-bye", "<unk>", "<unk>", "<eos>",
      "<unk>", "no", "<unk>", "<eos>",
    ]);
  });

  it("reproduces Python's counts on the shipped corpus: 19,071 ids, 3,071 <eos>", () => {
    const vocab = buildVocab("dolch", "full", corpusText);
    const stream = tokenStream(corpusText, vocab);
    expect(stream.length).toBe(19071);
    expect(stream.filter((id) => id === 2).length).toBe(3071);
    // The flat encoding is the OLD, wrong stream — kept here so the difference is visible
    // rather than merely asserted away.
    expect(vocab.encodeText(corpusText).length).toBe(16000);
    expect(stream.length - vocab.encodeText(corpusText).length).toBe(3071);
  });

  it("is the stream the worker actually trains on", () => {
    const messages: LexTrainResponse[] = [];
    runTrainingJob(
      {
        text: corpusText,
        budgetSource: "dolch",
        budget: "full",
        model: { dModel: 16, nLayers: 1, nHeads: 1, ctx: 32 },
        steps: 1,
        batchSize: 2,
        seed: 1,
        sampleEvery: 0,
      },
      (m) => messages.push(m),
    );
    const done = messages.find((m) => m.type === "done");
    expect(done?.type).toBe("done");
    if (done?.type !== "done") throw new Error("no done message");
    expect(done.nTokens).toBe(19071);
  });
});

// --- training ------------------------------------------------------------------------

describe("training schedule and batching", () => {
  it("rounds like Python (half to even) so the warm-up length matches", () => {
    // Python: round(0.5)==0, round(1.5)==2, round(2.5)==2, round(-0.5)==0. Naive
    // Math.round would give 1, 2, 3, -0 and shift the warm-up by a step.
    expect([0.5, 1.5, 2.5, 3.5, -0.5, 2.4, 2.6].map(pyRound)).toEqual([0, 2, 2, 4, 0, 2, 3]);
  });

  it("peaks the one-cycle schedule at `lr` and anneals to lr/25/1e4", () => {
    const steps = 400;
    const peak = 3e-3;
    const initial = peak / 25;
    expect(oneCycleLr(0, steps, peak)).toBeCloseTo(initial, 12);
    const w = pyRound(0.3 * steps);
    expect(w).toBe(120);
    expect(oneCycleLr(w, steps, peak)).toBeCloseTo(peak, 12);
    const values = Array.from({ length: steps }, (_, i) => oneCycleLr(i, steps, peak));
    expect(Math.max(...values)).toBeCloseTo(peak, 12);
    // Monotone up to the peak, monotone down after it.
    for (let i = 1; i < w; i++) expect(values[i]).toBeGreaterThan(values[i - 1]);
    for (let i = w + 1; i < steps; i++) expect(values[i]).toBeLessThan(values[i - 1]);
    expect(values[steps - 1]).toBeGreaterThan(initial / 1e4);
    expect(values[steps - 1]).toBeLessThan(initial);
  });

  it("splits 95/5 and never samples a window that runs off the end", () => {
    const tokens = Int32Array.from({ length: 1000 }, (_, i) => (i % 17) + 4);
    const { train, val } = splitTokens(tokens);
    expect(train.length).toBe(950);
    expect(val.length).toBe(50);
    expect(Array.from(val.slice(0, 3))).toEqual([(950 % 17) + 4, (951 % 17) + 4, (952 % 17) + 4]);

    let seed = 1;
    const rand = () => {
      seed = (seed * 16807) % 2147483647;
      return seed / 2147483647;
    };
    const batch = sampleBatch(train, 64, 8, rand);
    expect(batch.ids.length).toBe(8 * 64);
    expect(batch.targets.length).toBe(8 * 64);
    // targets are the inputs shifted by one, within each window.
    for (let b = 0; b < 8; b++) {
      for (let t = 0; t < 63; t++) {
        expect(batch.targets[b * 64 + t]).toBe(batch.ids[b * 64 + t + 1]);
      }
    }
  });
});

describe("a real training run", () => {
  const vocab = buildVocab("dolch", "primer", corpusText);
  const tokens = vocab.encodeText(corpusText);
  const cfg = defaultConfig(vocab.rows, { dModel: 16, nLayers: 1, nHeads: 2, ctx: 32 });

  it("reduces the loss", () => {
    const result = runTraining({ cfg, tokens, steps: 60, batchSize: 8, seed: 3, evalEvery: 0, sampleEvery: 0 });
    // eslint-disable-next-line no-console
    console.log(
      `  training: |V|=${vocab.budgetSize} rows=${vocab.rows} tokens=${tokens.length} ` +
        `loss ${result.initialTrainLoss.toFixed(4)} -> ${result.finalTrainLoss.toFixed(4)}`,
    );
    expect(result.history.length).toBe(60);
    expect(Number.isFinite(result.initialTrainLoss)).toBe(true);
    expect(result.finalTrainLoss).toBeLessThan(result.initialTrainLoss);
    // A fresh model is near-uniform over the rows: ln(96) ~ 4.56.
    expect(result.initialTrainLoss).toBeGreaterThan(4);
    expect(result.initialTrainLoss).toBeLessThan(Math.log(vocab.rows) + 0.5);
    // The reported final loss is a real forward pass, not the last batch's number.
    const model = new LexModel(cfg, result.weights);
    expect(evalLoss(model, splitTokens(tokens).train)).toBeCloseTo(result.finalTrainLoss, 12);
  });

  it("leaves the caller's weights untouched when continuing from them", () => {
    const base = initWeights(cfg, 3);
    const before = Float32Array.from(base.embed);
    runTraining({ cfg, tokens, steps: 3, batchSize: 4, seed: 3, initialWeights: base, evalEvery: 0, sampleEvery: 0 });
    expect(Array.from(base.embed)).toEqual(Array.from(before));
  });
});

// --- generation ----------------------------------------------------------------------

describe("generation", () => {
  it("produces zero out-of-budget words at every Dolch budget size", () => {
    for (const name of DOLCH_ORDER) {
      const vocab = buildVocab("dolch", name, corpusText);
      const budget = new Set(vocab.words);
      const cfg = defaultConfig(vocab.rows, { dModel: 16, nLayers: 1, nHeads: 2, ctx: 16 });
      // Briefly but really trained: an untrained model can pick `<eos>` immediately and
      // emit nothing, which would make "zero out-of-budget words" a vacuous claim.
      const trained = runTraining({
        cfg,
        tokens: vocab.encodeText(corpusText),
        steps: 15,
        batchSize: 4,
        seed: 8,
        evalEvery: 0,
        sampleEvery: 0,
      });
      const model = new LexModel(cfg, trained.weights);
      let totalWords = 0;
      for (const temperature of [0, 0.7, 1.5]) {
        const out = generate(model, vocab, {
          prompt: "the little cat",
          temperature,
          maxNewTokens: 60,
          seed: 4,
        });
        expect(out.ids.length).toBeGreaterThan(0);
        totalWords += out.words.length;
        for (const w of out.words) {
          expect(budget.has(w), `${name} @ T=${temperature} emitted out-of-budget ${JSON.stringify(w)}`).toBe(true);
        }
        // Re-tokenizing the rendered text must not resurrect anything either.
        for (const t of tokenize(out.text)) expect(budget.has(t)).toBe(true);
        // The banned ids never appear in the raw stream.
        for (const id of out.ids) {
          if (id !== 2) expect((GENERATION_BANNED_IDS as readonly number[]).includes(id)).toBe(false);
        }
      }
      expect(totalWords, `${name} produced no words at any temperature`).toBeGreaterThan(0);
    }
  });

  it("is greedy and deterministic at temperature 0, and seeded above it", () => {
    const vocab = buildVocab("dolch", "pre_primer", corpusText);
    const cfg = defaultConfig(vocab.rows, { dModel: 16, nLayers: 1, nHeads: 2, ctx: 16 });
    const model = LexModel.fresh(cfg, 6);
    const a = generate(model, vocab, { temperature: 0, maxNewTokens: 12 });
    const b = generate(model, vocab, { temperature: 0, maxNewTokens: 12, seed: 999 });
    expect(a.ids).toEqual(b.ids);
    const c = generate(model, vocab, { temperature: 1, maxNewTokens: 12, seed: 1 });
    const cAgain = generate(model, vocab, { temperature: 1, maxNewTokens: 12, seed: 1 });
    expect(c.ids).toEqual(cAgain.ids);
  });

  it("reports prompt words the budget cannot express instead of hiding them", () => {
    const vocab = buildVocab("dolch", "pre_primer", corpusText);
    const cfg = defaultConfig(vocab.rows, { dModel: 16, nLayers: 1, nHeads: 2, ctx: 16 });
    const model = LexModel.fresh(cfg, 6);
    const out = generate(model, vocab, { prompt: "the perambulator is blue", maxNewTokens: 4, seed: 2 });
    // `the`, `is` and `blue` are all pre-primer words; `perambulator` is not.
    expect(out.promptOov).toEqual(["perambulator"]);
    expect(out.promptIds).toContain(0); // <unk>
  });

  /**
   * "In budget by construction" is only true while the arithmetic is. With non-finite
   * weights every logit is NaN, and `NaN > -Infinity` is FALSE — so the greedy argmax
   * fell through to its initialiser `next = 0`, which is `<unk>`, bypassing the -inf ban
   * entirely, while the sampler fell through to `V - 1`. Stripping specials from `words`
   * then hid it: the tab printed 40 words with an "every one drawn from the budget"
   * badge, and at T=0 printed "0 tokens", both with no error. Python raises
   * `ComputeError` in both cases; so must this.
   *
   * The state is reachable by clicking: a `×2` preset applied ~140 times, or one cell
   * edit of `1e40` — finite in JS, and therefore accepted, but `Infinity` once stored in
   * a `Float32Array`.
   */
  describe("weights that have left float32 range", () => {
    const vocab = buildVocab("dolch", "pre_primer", corpusText);
    const cfg = defaultConfig(vocab.rows, { dModel: 16, nLayers: 1, nHeads: 2, ctx: 16 });

    const overflowed = (): ReturnType<typeof initWeights> => {
      const w = initWeights(cfg, 6);
      w["layers.0.fc1_w"][0] = 1e40; // Number.isFinite(1e40) === true; stored as Infinity
      expect(Number.isFinite(w["layers.0.fc1_w"][0])).toBe(false);
      return w;
    };

    const nanWeights = (): ReturnType<typeof initWeights> => {
      const w = initWeights(cfg, 6);
      w.embed[3] = NaN;
      return w;
    };

    for (const [label, make] of [
      ["an edit that overflowed to Infinity", overflowed],
      ["an edit that produced NaN", nanWeights],
    ] as const) {
      it(`refuses to generate at T=0 and at T>0 after ${label}`, () => {
        const model = new LexModel(cfg, make());
        for (const temperature of [0, 0.9]) {
          let caught: unknown = null;
          try {
            generate(model, vocab, { temperature, maxNewTokens: 40, seed: 4 });
          } catch (e) {
            caught = e;
          }
          expect(caught, `T=${temperature} returned instead of throwing`).toBeInstanceOf(Error);
          const err = caught as Error & { type?: string };
          expect(err.type).toBe("ComputeError");
          // The message must name the cause, not just the symptom.
          expect(err.message).toMatch(/not finite|non-finite/);
          expect(err.message).toMatch(/weight edit|float32 range/);
        }
      });
    }

    it("refuses to train from them, naming the cause rather than blaming the learning rate", () => {
      const tokens = tokenStream(corpusText, vocab);
      let caught: unknown = null;
      try {
        runTraining({ cfg, tokens, steps: 2, batchSize: 2, seed: 1, initialWeights: overflowed() });
      } catch (e) {
        caught = e;
      }
      expect(caught).toBeInstanceOf(Error);
      const err = caught as Error & { type?: string };
      expect(err.type).toBe("ComputeError");
      expect(err.message).toMatch(/layers\.0\.fc1_w/);
      expect(err.message).toMatch(/non-finite/);
      expect(err.message).not.toMatch(/lower learning rate/);
    });

    it("refuses a fine-tune through the worker job for the same reason", () => {
      const messages: LexTrainResponse[] = [];
      expect(() =>
        runTrainingJob(
          {
            text: corpusText,
            budgetSource: "dolch",
            budget: "pre_primer",
            vocabWords: [...vocab.words],
            model: { ...cfg },
            initialWeights: overflowed(),
            steps: 2,
            batchSize: 2,
            seed: 1,
            sampleEvery: 0,
          },
          (m) => messages.push(m),
        ),
      ).toThrow(/non-finite/);
      expect(messages.find((m) => m.type === "done")).toBeUndefined();
    });
  });

  it("refuses a vocabulary the model was not built for", () => {
    const vocab = buildVocab("dolch", "full", corpusText);
    const small = buildVocab("dolch", "primer", corpusText);
    const model = LexModel.fresh(defaultConfig(vocab.rows, { dModel: 8, nLayers: 1, nHeads: 2, ctx: 8 }), 1);
    expect(() => generate(model, small, {})).toThrow(/rows/);
  });
});

// --- the worker job ------------------------------------------------------------------

describe("the training job the worker runs", () => {
  it("returns weights, vocabulary and coverage together, so they cannot be mismatched", () => {
    const messages: LexTrainResponse[] = [];
    runTrainingJob(
      {
        text: corpusText,
        budgetSource: "dolch",
        budget: "pre_primer",
        model: { dModel: 16, nLayers: 1, nHeads: 2, ctx: 16 },
        steps: 8,
        batchSize: 4,
        seed: 1,
        sampleEvery: 4,
        samplePrompt: "the little",
        sampleMaxNewTokens: 8,
      },
      (m) => messages.push(m),
    );
    const done = messages.find((m) => m.type === "done");
    expect(done, "the job never reported done").toBeDefined();
    if (done?.type !== "done") throw new Error("unreachable");
    expect(done.vocabWords.length).toBe(40);
    expect(done.config.vocabRows).toBe(44);
    expect(done.coverage.total_tokens).toBeGreaterThan(1000);
    expect(done.history.length).toBe(8);
    expect(messages.filter((m) => m.type === "progress").length).toBe(8);
    expect(messages.filter((m) => m.type === "sample").length).toBe(2);

    // The returned weights + vocabulary really do reconstruct a working model.
    const vocab = new LexVocab(done.vocabWords, "dolch", done.budgetName);
    const model = new LexModel(done.config, done.weights);
    const budget = new Set(done.vocabWords);
    for (const w of generate(model, vocab, { seed: 1, maxNewTokens: 20 }).words) {
      expect(budget.has(w)).toBe(true);
    }
    // ... and its embedding has a spectrum below the ceiling.
    const s = spectrum(done.weights.embed, done.config.vocabRows, done.config.dModel);
    expect(s.effectiveRank).toBeGreaterThan(0);
    expect(s.effectiveRank).toBeLessThanOrEqual(s.ceiling + 1e-9);
  });

  it("drives the whole run through trainInWorker and can fine-tune the result", async () => {
    const vocab = buildVocab("dolch", "pre_primer", corpusText);
    const seen: TrainProgress[] = [];
    const first = await trainInWorker(
      {
        vocab,
        text: corpusText,
        dModel: 16,
        nLayers: 1,
        nHeads: 2,
        ctx: 16,
        steps: 10,
        batch: 4,
        seed: 1,
        sampleEvery: 5,
        sampleMaxNewTokens: 8,
      },
      (p) => seen.push(p),
    );
    expect(first.steps).toBe(10);
    expect(seen.filter((p) => p.sample === undefined).length).toBe(10);
    expect(seen.filter((p) => p.sample !== undefined).length).toBe(2);
    expect(seen[seen.length - 1].totalSteps).toBe(10);
    expect(first.model.vocabWords).toEqual([...vocab.words]);

    // Fine-tuning keeps the model's own vocabulary and continues from its weights.
    const before = Float32Array.from(first.model.weights.embed);
    const second = await trainInWorker({
      vocab,
      text: corpusText,
      dModel: 16,
      nLayers: 1,
      nHeads: 2,
      ctx: 16,
      steps: 5,
      batch: 4,
      seed: 2,
      initFrom: first.model,
      sampleEvery: 0,
    });
    expect(second.model.vocabWords).toEqual(first.model.vocabWords);
    expect(Array.from(first.model.weights.embed)).toEqual(Array.from(before)); // untouched
    expect(Array.from(second.model.weights.embed)).not.toEqual(Array.from(before));
    expect(second.model.initialLoss).toBeCloseTo(first.model.finalLoss, 12);

    // The bundle rebuilds into a working, in-budget model.
    const budget = new Set(second.model.vocabWords);
    for (const w of generate(modelOf(second.model), vocabOf(second.model), { seed: 3, maxNewTokens: 20 }).words) {
      expect(budget.has(w)).toBe(true);
    }
  });

  it("refuses to fine-tune across a change of budget", async () => {
    const small = buildVocab("dolch", "pre_primer", corpusText);
    const big = buildVocab("dolch", "primer", corpusText);
    const trained = await trainInWorker({
      vocab: small,
      text: corpusText,
      dModel: 8,
      nLayers: 1,
      nHeads: 2,
      ctx: 16,
      steps: 2,
      batch: 2,
      sampleEvery: 0,
    });
    await expect(
      trainInWorker({ vocab: big, text: corpusText, dModel: 8, nLayers: 1, nHeads: 2, ctx: 16, steps: 2, initFrom: trained.model }),
    ).rejects.toThrow(/embedding rows/);
  });
});

/**
 * The request the Train panel actually posts when you press Fine-tune (FR-619).
 *
 * It does not go through `trainInWorker`; it builds a `LexTrainRequest` by hand with
 * `initialWeights` and an explicit `vocabWords`, and hands it to the worker. What must
 * hold is that the EXPLICIT word list wins over the budget fields beside it — feature
 * 004's issue #6 was a fine-tune that quietly rebuilt the vocabulary from the new text,
 * after which every embedding row meant a different word than the weights expected.
 */
describe("fine-tuning through the worker keeps the active model's vocabulary", () => {
  function drive(req: Parameters<typeof runTrainingJob>[0]) {
    const seen: LexTrainResponse[] = [];
    runTrainingJob(req, (m) => seen.push(m));
    const done = seen.find((m) => m.type === "done");
    if (done?.type !== "done") throw new Error("the worker produced no done message");
    return done;
  }

  it("uses the word list it was given, not the one the budget fields would build", () => {
    const active = buildVocab("dolch", "pre_primer", corpusText);
    const model = { dModel: 8, nLayers: 1, nHeads: 2, ctx: 16 };
    const first = drive({
      text: corpusText,
      budgetSource: "dolch",
      budget: "pre_primer",
      vocabWords: [...active.words],
      model,
      steps: 2,
      batchSize: 2,
      sampleEvery: 0,
    });

    // The panel's fine-tune request: the SAME vocabulary, the previous weights, and
    // budget fields that (deliberately) name a LARGER budget. The explicit list wins.
    const second = drive({
      text: corpusText,
      budgetSource: "dolch",
      budget: "primer",
      vocabWords: [...active.words],
      initialWeights: first.weights,
      model,
      steps: 2,
      batchSize: 2,
      sampleEvery: 0,
    });

    expect(second.vocabWords).toEqual([...active.words]);
    expect(second.config.vocabRows).toBe(first.config.vocabRows);
    expect(dolchBudget("primer").length).toBeGreaterThan(active.words.length); // the trap was real
    // It continued from those weights rather than re-initializing: a 2-step run from a
    // fresh init would not start at the trained model's loss.
    expect(second.initialTrainLoss).toBeCloseTo(first.finalTrainLoss, 6);
    // And it can still only speak in budget.
    const budget = new Set(second.vocabWords);
    const vocab = new LexVocab(second.vocabWords, "dolch", second.budgetName);
    for (const w of generate(new LexModel(second.config, second.weights), vocab, { seed: 4 }).words) {
      expect(budget.has(w)).toBe(true);
    }
  });
});
