/**
 * Golden-vector parity: the TypeScript Lexicon Lab engine vs the real PyTorch one.
 *
 * SC-605 of `specs/006-lexicon-lab-tiny/spec.md` requires the two implementations of
 * `specs/006-lexicon-lab-tiny/architecture.md` to agree to <= 1e-5. This file is that
 * proof. It follows the pattern feature 003 established for the Geometry Lab
 * (`scripts/export_static_assets.py` -> `tests/fixtures/geo/golden.json` ->
 * `geoEngine.test.ts`): a Python script runs the REAL backend and writes what it
 * measured; this test runs the REAL browser engine against the same inputs and asserts.
 *
 * The fixture is `tests/fixtures/lex-golden.json`, regenerated by
 *
 *     python scripts/export_lex_golden.py
 *
 * and it records the git sha, the command, and each case's configuration.
 *
 * Coverage, across three configurations that vary d_model, n_layers, n_heads and
 * tied/untied together:
 *
 *   1. a FIXED weight set, spelled out in the fixture, so both engines start from
 *      identical numbers — architecture.md explicitly does not claim RNG parity
 *      ("non-portable RNG streams"), so seeded-init agreement would prove nothing;
 *   2. forward-pass logits for a fixed token sequence;
 *   3. the loss for a fixed (input, target) pair, with a `<pad>` target so
 *      `ignore_index` is exercised;
 *   4. every spectrum statistic — effective/stable rank, participation ratio,
 *      frac_var_top2/top10, n_dims_for_90pct, the ceiling, the leading singular values,
 *      and the PCA coordinates + explained-variance ratios;
 *   5. real gradients, their global norm, and the weights after ONE AdamW step at a
 *      known LR, so the training math is covered and not only inference;
 *   6. the one-cycle LR schedule at several step indices.
 *
 * DEVIATION METRIC. Every comparison reports
 *
 *     dev = |actual - golden| / max(1, |actual|, |golden|)
 *
 * i.e. relative deviation for order-1-and-larger quantities, absolute deviation for
 * small ones — a single number that is <= 1e-5 only if BOTH readings are. The measured
 * maximum per category is printed at the end of the run.
 *
 * Note on precision: the backend computes in float32 and this engine in float64 (the
 * geoEngine house convention), so exact equality is neither expected nor claimed; 1e-5
 * is the contract's tolerance and it is asserted here, never widened.
 *
 * ONE MEASURED EXCEPTION, and it is a property of AdamW rather than of either engine.
 * On the FIRST step, `t = 1` makes `m̂ = g` and `sqrt(v̂) = |g|`, so the update is
 *
 *     -lr · g / (|g| + 1e-8)
 *
 * which for any `|g|` above the epsilon is `-lr · sign(g)` REGARDLESS of the gradient's
 * magnitude. A parameter whose true gradient is at or below that epsilon therefore has
 * its step decided by each backend's roundoff, and float32 vs float64 disagree there by
 * up to a full `lr`. The largest such family is structural and provably so: the KEY BIAS
 * `qkv_b[d:2d]` has an EXACTLY ZERO gradient, because adding a constant `b_k` to every
 * key shifts `scores_ij = q_i·k_j` by `q_i·b_k`, constant along `j`, and softmax is
 * invariant to a constant shift along the axis it normalizes. This engine computes ~1e-18
 * there and torch's float32 computes ~1e-9; both are zero, and AdamW amplifies the
 * difference to ~1e-4.
 *
 * So post-step weights are split by the optimizer's OWN constant: entries whose golden
 * gradient has `|g| >= ADAM_EPS` are held to 1e-5 (measured worst: 2.1e-6 across all
 * three configurations); entries below it are held to the bound a single step can move
 * them, and their count is asserted to stay a small fraction so the exception can never
 * quietly grow to hide a real regression. Nothing else in this file is exempted.
 */

import { afterAll, describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";

import {
  LexModel,
  backward,
  crossEntropy,
  decayedWeightNames,
  zeroGrads,
  type LexConfig,
  type WeightSet,
} from "../../src/lib/lexEngine/model";
import { ADAM_EPS, oneCycleLr, runTraining } from "../../src/lib/lexEngine/train";
import { spectrum } from "../../src/lib/lexEngine/spectrum";

// --- the fixture ---------------------------------------------------------------------

const FIXTURE = path.resolve(__dirname, "../fixtures/lex-golden.json");

interface GoldenCase {
  name: string;
  config: {
    vocab_rows: number;
    d_model: number;
    n_layers: number;
    n_heads: number;
    ctx: number;
    tied: boolean;
    dropout: number;
  };
  param_count: number;
  n_parameters_measured: number;
  weight_names: string[];
  weights: Record<string, string>;
  forward: { B: number; T: number; ids: number[]; logits: number[][] };
  loss: { B: number; T: number; ids: number[]; targets: number[]; value: number; n_valid: number };
  spectrum: Record<string, GoldenSpectrum>;
  optimizer_step: {
    stream: number[];
    n_train: number;
    batch_size: number;
    steps: number;
    peak_lr: number;
    scheduled_lr: number;
    weight_decay: number;
    decayed: string[];
    loss: number;
    grad_norm: number;
    grad_norm_recomputed: number;
    grads: Record<string, string>;
    weights_after: Record<string, string>;
  };
}

interface GoldenSpectrum {
  rows: number;
  d_model: number;
  max_rank: number;
  eigenvalues: number[];
  singular_values: number[];
  explained_variance: number[];
  total_variance: number;
  effective_rank: number;
  stable_rank: number;
  participation_ratio: number;
  frac_var_top2: number;
  frac_var_top10: number;
  n_dims_for_90pct: number;
  pca_coords: number[][];
  pca_explained_variance_ratio: number[];
  degenerate: boolean;
}

interface GoldenFile {
  format: string;
  generated: string;
  git_sha: string;
  command: string;
  tolerance: number;
  schedule: { total_steps: number; peak_lr: number; points: { step: number; lr: number }[] }[];
  cases: GoldenCase[];
}

const golden = JSON.parse(fs.readFileSync(FIXTURE, "utf-8")) as GoldenFile;

/** The tolerance SC-605 sets. Read from the fixture so the two cannot drift apart. */
const TOL = golden.tolerance;

// --- decoding ------------------------------------------------------------------------

/**
 * Base64 little-endian float32 -> Float32Array. The bytes are copied rather than
 * viewed in place: a Buffer's byteOffset is not guaranteed to be 4-byte aligned, and
 * `new Float32Array(buf.buffer, buf.byteOffset, n)` throws when it is not.
 */
function decodeF32(b64: string): Float32Array {
  const bytes = Uint8Array.from(Buffer.from(b64, "base64"));
  const copy = new Uint8Array(bytes.length);
  copy.set(bytes);
  return new Float32Array(copy.buffer);
}

/**
 * The two engines name the same tensor differently — Python's `nn.ModuleList` is
 * `blocks`, the TypeScript engine's is `layers` — so the fixture's Python keys are
 * translated here rather than either implementation being bent to match the other.
 */
function toEngineName(pythonName: string): string {
  return pythonName.replace(/^blocks\./, "layers.");
}

function decodeWeights(encoded: Record<string, string>): WeightSet {
  const out: WeightSet = {};
  for (const [name, b64] of Object.entries(encoded)) out[toEngineName(name)] = decodeF32(b64);
  return out;
}

function toEngineConfig(c: GoldenCase["config"]): LexConfig {
  return {
    vocabRows: c.vocab_rows,
    dModel: c.d_model,
    nLayers: c.n_layers,
    nHeads: c.n_heads,
    ctx: c.ctx,
    tied: c.tied,
    dropout: c.dropout,
  };
}

// --- deviation tracking --------------------------------------------------------------

interface Worst {
  dev: number;
  where: string;
  actual: number;
  golden: number;
}

const worst = new Map<string, Worst>();

function deviation(actual: number, expected: number): number {
  if (actual === expected) return 0;
  return Math.abs(actual - expected) / Math.max(1, Math.abs(actual), Math.abs(expected));
}

/** Record one comparison under `category` and fail immediately if it exceeds TOL. */
function close(category: string, where: string, actual: number, expected: number): void {
  if (!Number.isFinite(actual) || !Number.isFinite(expected)) {
    throw new Error(`${category} ${where}: non-finite value (${actual} vs ${expected})`);
  }
  const dev = deviation(actual, expected);
  const prev = worst.get(category);
  if (!prev || dev > prev.dev) worst.set(category, { dev, where, actual, golden: expected });
  if (dev > TOL) {
    throw new Error(
      `${category} ${where}: |${actual} - ${expected}| = ${Math.abs(actual - expected)}, ` +
        `deviation ${dev.toExponential(3)} > tolerance ${TOL}`,
    );
  }
}

function closeVec(category: string, where: string, actual: ArrayLike<number>, expected: number[]): void {
  expect(actual.length, `${category} ${where}: length`).toBe(expected.length);
  for (let i = 0; i < expected.length; i++) close(category, `${where}[${i}]`, actual[i], expected[i]);
}

afterAll(() => {
  const rows = [...worst.entries()].sort((a, b) => b[1].dev - a[1].dev);
  const lines = rows.map(([category, w]) => {
    const detail = Number.isFinite(w.actual) ? `${w.where}: ${w.actual} vs ${w.golden}` : w.where;
    return `  ${category.padEnd(38)} max dev ${w.dev.toExponential(3)}  (${detail})`;
  });
  // eslint-disable-next-line no-console
  console.log(
    `\nlex golden parity vs PyTorch (git ${golden.git_sha.slice(0, 8)}, tolerance ${TOL}):\n` +
      lines.join("\n") +
      "\n",
  );
});

// --- provenance ----------------------------------------------------------------------

describe("lex golden fixture", () => {
  it("records its provenance, so a stale fixture is visible rather than silent", () => {
    expect(golden.format).toBe("lex-golden-v1");
    expect(golden.git_sha).toMatch(/^[0-9a-f]{40}$/);
    expect(golden.command).toContain("scripts/export_lex_golden.py");
    expect(golden.generated).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    expect(TOL).toBeLessThanOrEqual(1e-5);
  });

  it("covers at least 3 configurations varying d_model, n_layers, n_heads and tying", () => {
    expect(golden.cases.length).toBeGreaterThanOrEqual(3);
    const configs = golden.cases.map((c) => c.config);
    for (const key of ["d_model", "n_layers", "n_heads"] as const) {
      expect(new Set(configs.map((c) => c[key])).size, `cases must vary ${key}`).toBeGreaterThan(1);
    }
    expect(new Set(configs.map((c) => c.tied)).size, "cases must cover tied AND untied").toBe(2);
  });
});

// --- the one-cycle schedule ----------------------------------------------------------

describe("one-cycle LR schedule", () => {
  it("matches the backend at every sampled step index", () => {
    for (const { total_steps, peak_lr, points } of golden.schedule) {
      for (const { step, lr } of points) {
        close("schedule.lr", `S=${total_steps} peak=${peak_lr} i=${step}`, oneCycleLr(step, total_steps, peak_lr), lr);
      }
    }
  });

  it("puts the peak at the end of warmup and anneals below it afterwards", () => {
    // A guard on the golden itself: a schedule that never reaches its peak would match
    // a broken port just as happily as a correct one.
    const long = golden.schedule.find((s) => s.total_steps === 400)!;
    const peakPoint = long.points.find((p) => p.step === 120)!;
    expect(peakPoint.lr).toBeCloseTo(long.peak_lr, 12);
    expect(long.points.find((p) => p.step === 0)!.lr).toBeCloseTo(long.peak_lr / 25, 12);
    expect(long.points.find((p) => p.step === 399)!.lr).toBeLessThan(long.peak_lr / 25);
  });
});

// --- per-configuration parity --------------------------------------------------------

for (const gc of golden.cases) {
  describe(`lexEngine vs PyTorch [${gc.name}]`, () => {
    const cfg = toEngineConfig(gc.config);
    const weights = decodeWeights(gc.weights);
    const model = new LexModel(cfg, weights);
    const V = cfg.vocabRows;

    it("loads exactly the backend's weight set, at the backend's parameter count", () => {
      expect(Object.keys(weights).sort()).toEqual(gc.weight_names.map(toEngineName).sort());
      expect(model.nParams).toBe(gc.param_count);
      expect(model.nParams).toBe(gc.n_parameters_measured);
      // A tied model has NO head_w at all — the readout IS the embedding (FR-610).
      expect("head_w" in weights).toBe(!cfg.tied);
      expect(model.headWeight).toBe(cfg.tied ? weights.embed : weights.head_w);
    });

    it("reproduces the forward-pass logits for a fixed token sequence", () => {
      const { B, T, ids, logits } = gc.forward;
      const acts = model.forward(Int32Array.from(ids), B, T, {});
      expect(logits.length).toBe(B * T);
      for (let n = 0; n < B * T; n++) {
        closeVec("forward.logits", `[${n}]`, acts.logits.subarray(n * V, (n + 1) * V), logits[n]);
      }
    });

    it("reproduces the loss for a fixed (input, target) pair, ignoring <pad>", () => {
      const { B, T, ids, targets, value, n_valid } = gc.loss;
      const acts = model.forward(Int32Array.from(ids), B, T, {});
      const { ceSum, nValid } = crossEntropy(acts.logits, Int32Array.from(targets), B * T, V);
      expect(nValid, "non-pad target count").toBe(n_valid);
      expect(nValid).toBeLessThan(targets.length); // the pad really is being ignored
      close("loss", "value", ceSum / nValid, value);
    });

    describe("spectrum", () => {
      for (const [label, gs] of Object.entries(gc.spectrum)) {
        it(`reproduces every ${label} statistic`, () => {
          const matrix = label === "embedding" ? weights.embed : weights.head_w;
          const result = spectrum(matrix, gs.rows, gs.d_model);
          const tag = `${label}`;

          expect(gs.rows).toBe(V);
          expect(gs.degenerate, "a degenerate spectrum would make every ratio meaningless").toBe(false);

          // integer-valued quantities are compared EXACTLY
          expect(result.ceiling, `${tag}.ceiling`).toBe(gs.max_rank);
          expect(result.nDimsFor90pct, `${tag}.n_dims_for_90pct`).toBe(gs.n_dims_for_90pct);

          close("spectrum.scalars", `${tag}.total_variance`, result.totalVariance, gs.total_variance);
          close("spectrum.scalars", `${tag}.effective_rank`, result.effectiveRank, gs.effective_rank);
          close("spectrum.scalars", `${tag}.stable_rank`, result.stableRank, gs.stable_rank);
          close("spectrum.scalars", `${tag}.participation_ratio`, result.participationRatio, gs.participation_ratio);
          close("spectrum.scalars", `${tag}.frac_var_top2`, result.fracVarTop2, gs.frac_var_top2);
          close("spectrum.scalars", `${tag}.frac_var_top10`, result.fracVarTop10, gs.frac_var_top10);

          closeVec("spectrum.eigenvalues", `${tag}`, result.eigenvalues, gs.eigenvalues);
          closeVec("spectrum.singular_values", `${tag}`, result.singularValues, gs.singular_values);
          closeVec("spectrum.explained_variance", `${tag}`, result.eigenvalues.map((l) => l / result.totalVariance), gs.explained_variance);
          closeVec("spectrum.pca_evr", `${tag}`, result.explainedVarianceRatio, gs.pca_explained_variance_ratio);

          // PCA coordinates: a projection, and the place the eigenvector SIGN
          // convention of architecture.md § Spectrum step 6 either holds or does not.
          expect(gs.pca_coords.length).toBe(gs.rows);
          for (let r = 0; r < gs.rows; r++) {
            closeVec(
              "spectrum.pca_coords",
              `${tag}[${r}]`,
              result.coords.subarray(r * result.components, (r + 1) * result.components),
              gs.pca_coords[r],
            );
          }
        });
      }
    });

    /** The gradients of the step batch, from this engine's real backward pass. */
    function stepGradients(): Record<string, Float64Array> {
      const { B, T, ids, targets } = gc.loss;
      const acts = model.forward(Int32Array.from(ids), B, T, {});
      const { dLogits } = crossEntropy(acts.logits, Int32Array.from(targets), B * T, V);
      const grads = zeroGrads(cfg);
      backward(model, acts, dLogits, grads);
      return grads;
    }

    it("reproduces the backward pass: every gradient and their global norm", () => {
      const grads = stepGradients();
      let sq = 0;
      for (const [pyName, b64] of Object.entries(gc.optimizer_step.grads)) {
        const name = toEngineName(pyName);
        const expected = decodeF32(b64);
        const actual = grads[name];
        expect(actual, `missing gradient for ${name}`).toBeDefined();
        expect(actual.length, `${name}: gradient length`).toBe(expected.length);
        for (let i = 0; i < expected.length; i++) close("gradients.values", `${name}[${i}]`, actual[i], expected[i]);
        for (let i = 0; i < actual.length; i++) sq += actual[i] * actual[i];
      }
      close("gradients.global_norm", "norm", Math.sqrt(sq), gc.optimizer_step.grad_norm);
      // torch's clip_grad_norm_ return value and an independent sum of squares are two
      // different computations of the same number; the fixture carries both.
      close("gradients.global_norm", "recomputed", Math.sqrt(sq), gc.optimizer_step.grad_norm_recomputed);
    });

    it("computes a mathematically zero gradient for the key bias, as both engines must", () => {
      // The invariance this rests on: k_j -> k_j + b_k shifts scores_ij by q_i·b_k,
      // which is constant along j, and softmax ignores a constant shift along the axis
      // it normalizes. So d(loss)/d(qkv_b[d:2d]) is EXACTLY zero, and any nonzero value
      // either engine reports is its own roundoff. This is the reason for the
      // conditioning split in the AdamW test below, so it is checked rather than assumed.
      const grads = stepGradients();
      const d = cfg.dModel;
      for (let l = 0; l < cfg.nLayers; l++) {
        const ts = grads[`layers.${l}.qkv_b`];
        const py = decodeF32(gc.optimizer_step.grads[`blocks.${l}.qkv_b`]);
        let maxQ = 0;
        for (let i = 0; i < d; i++) maxQ = Math.max(maxQ, Math.abs(ts[i]));
        for (let i = d; i < 2 * d; i++) {
          expect(Math.abs(ts[i]), `layers.${l}.qkv_b[${i}] (key bias) should be ~0 here`).toBeLessThan(ADAM_EPS);
          expect(Math.abs(py[i]), `blocks.${l}.qkv_b[${i}] (key bias) should be ~0 in torch`).toBeLessThan(ADAM_EPS);
        }
        // ...while the QUERY bias, which is not gauge, carries a real gradient. Without
        // this the check above would also pass on a backward pass that returns nothing.
        expect(maxQ, `layers.${l}.qkv_b query slice should carry a real gradient`).toBeGreaterThan(1e-5);
      }
    });

    it("reproduces the weights after one real AdamW step at a known LR", () => {
      const step = gc.optimizer_step;
      // Both engines split the stream 95/5 and then have exactly ONE sampleable
      // window, so the batch is pinned without either side's RNG mattering — which is
      // the point, since architecture.md does not claim RNG parity.
      const result = runTraining({
        cfg,
        tokens: step.stream,
        steps: step.steps,
        lr: step.peak_lr,
        batchSize: step.batch_size,
        weightDecay: step.weight_decay,
        seed: 0,
        initialWeights: weights,
        sampleEvery: 0,
      });

      expect(result.history.length).toBe(step.steps);
      const point = result.history[0];
      close("optimizer.lr", "scheduled", point.lr, step.scheduled_lr);
      close("optimizer.loss", "step-1 loss", point.loss, step.loss);
      close("optimizer.grad_norm", "pre-clip norm", point.gradNorm, step.grad_norm);
      // The engine's own training loop must see the batch the golden was measured on.
      expect(point.loss).toBeCloseTo(gc.loss.value, 5);

      /**
       * The furthest one AdamW step can move a weight: |lr·g/(|g|+eps)| < lr, plus the
       * decoupled decay lr·wd·|p|. Two such steps can differ by at most twice that. An
       * entry whose gradient is below the optimizer's own epsilon is held to THIS bound
       * instead of to 1e-5 — see the file header for why no implementation can do better.
       */
      const reach = 2 * step.scheduled_lr * (1 + step.weight_decay);
      let noiseDetermined = 0;
      let total = 0;
      let worstNoiseDev = 0;

      for (const [pyName, b64] of Object.entries(step.weights_after)) {
        const name = toEngineName(pyName);
        const expected = decodeF32(b64);
        const goldenGrad = decodeF32(step.grads[pyName]);
        const actual = result.weights[name];
        expect(actual, `missing post-step weight ${name}`).toBeDefined();
        expect(actual.length, `${name}: post-step length`).toBe(expected.length);
        for (let i = 0; i < expected.length; i++) {
          total++;
          if (Math.abs(goldenGrad[i]) >= ADAM_EPS) {
            close("optimizer.weights_after", `${name}[${i}]`, actual[i], expected[i]);
          } else {
            noiseDetermined++;
            worstNoiseDev = Math.max(worstNoiseDev, deviation(actual[i], expected[i]));
            expect(
              Math.abs(actual[i] - expected[i]),
              `${name}[${i}]: gradient ${goldenGrad[i]} is below AdamW's epsilon, so the two ` +
                `steps may differ — but by at most one step's reach`,
            ).toBeLessThanOrEqual(reach);
          }
        }
      }

      // The escape hatch must stay small, or it stops being an escape hatch. Measured:
      // 0.4% (A), 1.5% (B), 0.5% (C) of parameters.
      expect(
        noiseDetermined / total,
        `${noiseDetermined}/${total} parameters had a below-epsilon gradient; that is too ` +
          "many for this exemption to be the documented AdamW conditioning effect",
      ).toBeLessThan(0.02);
      const prev = worst.get("optimizer.weights_after[below-eps grad]");
      if (!prev || worstNoiseDev > prev.dev) {
        worst.set("optimizer.weights_after[below-eps grad]", {
          dev: worstNoiseDev,
          where: `${gc.name}: ${noiseDetermined}/${total} params, bound ${reach.toExponential(2)}`,
          actual: NaN,
          golden: NaN,
        });
      }

      // The step must have MOVED the weights: comparing two identical tensors would
      // pass this test while proving nothing about the optimizer.
      const before = weights.embed;
      const after = result.weights.embed;
      let moved = 0;
      for (let i = 0; i < before.length; i++) if (before[i] !== after[i]) moved++;
      expect(moved, "the AdamW step changed no embedding weight").toBeGreaterThan(0);
    });

    it("decays exactly the 2-D weight matrices the backend decays", () => {
      // Not a numeric golden, but the split is part of the training math and a
      // mismatch here would show up only as a slow drift in a long run.
      const expected = gc.optimizer_step.decayed.map(toEngineName).sort();
      expect(decayedWeightNames(cfg).sort()).toEqual(expected);
    });
  });
}
