/**
 * Golden-vector parity for the VACANCY TRANSFORM: the TypeScript engine vs the real
 * Python one, on the real committed corpus.
 *
 * `specs/007-vacancy-transform-field/architecture.md` §11 requires this file and names
 * exactly what it must pin. SC-706 requires the two implementations to agree — strings and
 * id streams EXACTLY, floats within `tolerance`. This test is that proof, and it follows
 * `lexGolden.test.ts` (feature 006) and `geoEngine.test.ts` (feature 003): a Python script
 * runs the REAL backend and writes what it measured; this file runs the REAL browser
 * engine against the same inputs and asserts.
 *
 * The fixture is `tests/fixtures/vacancy-golden.json`, regenerated by
 *
 *     python scripts/export_vacancy_golden.py
 *
 * and it records the git sha, the command, the corpus digest and each case's parameters.
 * `TOLERANCE` is read FROM the file rather than declared here, so the exporter and this
 * test cannot drift apart — the same discipline `lexGolden.test.ts` keeps.
 *
 * WHAT IS PINNED, per §11:
 *
 *   1. `vacancyU` for 24 stems spanning eligible/ineligible and both budgets, compared as
 *      the EXACT double. That exactness is the point of departure 2 (§4): `u` shifts a
 *      64-bit digest right by 11 before dividing by 2^53, so the numerator is exactly
 *      representable and Python and JavaScript get THE SAME double rather than two
 *      neighbours that straddle a `p` boundary.
 *   2. The FULL stem -> nonce map at seed 0 and seed 7 — every pair, both directions of
 *      the size check, plus `remintRounds` / `bijective` / `imageSize`.
 *   3. The first 400 characters of the vacated corpus at each `p`, exactly; plus the
 *      sha256 of the WHOLE 86 kB rewrite, which is the same assertion at 64 bytes.
 *   4. Every §10 statistic, at `p in {0, 0.25, 0.35, 0.5, 0.7, 0.75, 1}` and both seeds.
 *   5. Nesting as explicit SETS: `vacated(0.35) ⊆ vacated(0.7) ⊆ vacated(1)`, checked
 *      against the literal stem lists rather than against an assertion this language makes
 *      about itself (SC-701).
 *   6. Stability: each pinned stem's surface form at every `p`, and — derived across the
 *      cases — the fact that it is byte-identical at every `p` where the stem is vacated
 *      (SC-702).
 *   7. The token-id-stream digest under the mapped vocabulary at each `p`. All of them are
 *      EQUAL, across both seeds and both `matchProsody` settings: the invariance theorem
 *      of §7.3 / SC-703 pinned as DATA rather than as an assertion written twice.
 *   8. Both control conditions and both `matchProsody` settings.
 *
 * COMPARISON RULE. Strings, digests, counts, booleans and `u` are compared with `toBe` —
 * exact. Only the six prosody means (`meanSyllables*`, `meanAnapest*`, `stressFrom*`) use
 * `tolerance`, and the measured worst deviation is printed at the end of the run so a
 * silent creep toward the bound is visible.
 *
 * NO KNOWN DIVERGENCES REMAIN. Every case here — both seeds, both `matchProsody` settings,
 * every `p`, and all three controls — agrees field for field, string for string, digest for
 * digest. Three earlier disagreements were pinned in this file rather than hidden, and each
 * was retired by fixing the stack the contract said was wrong, never by loosening a
 * comparison:
 *
 *   1. `control-reveal-after-2`: `corpusTypesVacated` read 665 in Python and 1337 here,
 *      because Python MEASURED the count from the two texts while this engine computed it
 *      through the map. §10 defines `corpusTypes*` as what the panel shows a READER — i.e.
 *      what the text does — so the measured reading was the contract's. `vacancyStats` now
 *      measures the texts; `domainTypes*` keeps map membership, which §10 also requires.
 *   2. `control-inconsistent`: the two stacks minted DIFFERENT per-occurrence nonces. §5.8
 *      pins the key as `${stem}#${idx}` and §5.5's mint read its stress pattern off the
 *      string it was handed, so Python got `stress("little#0") = "10"` where this engine
 *      gets `stress("little") = "100"` — `Little` minted as `Wrerken` there and `Wrerkenle`
 *      here. §7.1 says the nonce carries THE STEM's syllable count and stress, so the key
 *      must not reach the prosody lookup; Python's `_mint` now takes `stem` separately.
 *   3. Condition B on the per-occurrence path (§5.8). It was enforced when building the map
 *      and not in the `consistent = false` control, so at seed 7, `p = 1`, the stem `tak`
 *      minted the nonce `tak` and `Taking -> Taking`: one token silently failed to vacate.
 *      Both stacks now forbid a per-occurrence nonce from equalling the stem it replaces as
 *      well as any domain type, and `control-inconsistent-seed7` pins the result — 1922
 *      corpus types and 8202 tokens vacated, exactly what `consistent = true` reads.
 *
 * The `knownDivergence` mechanism itself stays: it carries both readings per field, this
 * test asserts each side against its own, and `attach_divergence` in the exporter refuses to
 * write a fixture at all once Python starts agreeing with a recorded TypeScript value. That
 * guard is what retired all three entries above, and it is what an outstanding cross-stack
 * defect would use again.
 */

import { afterAll, describe, expect, it } from "vitest";
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import { LexVocab, dolchBudget, tokenize } from "../../src/lib/lexEngine";
import { tokenStream } from "../../src/lib/lexEngine/train";
import {
  buildVacancyMap,
  effectiveKeepSet,
  isEligible,
  mapVocabWords,
  stemAndSuffix,
  transformWord,
  typeCounts,
  vacancyDomain,
  vacancyParams,
  vacancyStats,
  vacancyU,
  vacateText,
  type VacancyMap,
  type VacancyParams,
  type VacancyStats,
} from "../../src/lib/lexEngine/vacancy";
import type { LexCorpusAsset } from "../../src/lib/staticClient/lex";

// --- the fixture ----------------------------------------------------------------------

interface GoldenStem {
  stem: string;
  eligible: boolean;
  stemOf: string;
  suffixOf: string;
  inDomain: boolean;
  inCorpus: boolean;
  inDolchFull: boolean;
  u: Record<string, number>;
}

interface GoldenMap {
  label: string;
  seed: number;
  matchProsody: boolean;
  mint: "nonce" | "swap";
  injectiveAtEveryP: boolean;
  remintRounds: number;
  bijective: boolean;
  imageSize: number;
  domainSize: number;
  mappingSize: number;
  mappingSha256: string;
  mapping: Record<string, string> | null;
  sampleNonces?: Record<string, string | null>;
}

interface GoldenIdStream {
  digest: string;
  length: number;
  first16: number[];
  last16: number[];
  mappedWordsSha256: string;
}

/** One field the two stacks disagree on, with BOTH readings — see the header. */
interface GoldenDivergentField {
  /** Either a case key (`head400`, `vacatedSha256`, `vacatedChars`) or `stats.<name>`. */
  field: string;
  python: string | number;
  typescript: string | number;
}

interface GoldenDivergence {
  cause: string;
  status: string;
  fields: GoldenDivergentField[];
}

interface GoldenCase {
  label: string;
  map: string;
  params: {
    p: number;
    seed: number;
    consistent: boolean;
    matchProsody: boolean;
    revealAfter: number;
    keep: string[];
    mint: "nonce" | "swap";
  };
  head400: string;
  vacatedSha256: string;
  vacatedChars: number;
  stats: Record<string, number | boolean>;
  stemForms: Record<string, string> | null;
  idStream: GoldenIdStream | null;
  mapVocabWordsRejects: boolean;
  knownDivergence?: GoldenDivergence;
}

interface Golden {
  format: string;
  generated: string;
  git_sha: string;
  command: string;
  contract: string;
  tolerance: number;
  corpus: {
    sha256: string;
    chars: number;
    tokens: number;
    corpusTypes: number;
    domainSize: number;
    budget: string;
    budgetSize: number;
  };
  stems: GoldenStem[];
  maps: GoldenMap[];
  cases: GoldenCase[];
  nesting: { seed: number; map: string; levels: { p: number; stems: string[] }[] };
}

const FIXTURE = path.resolve(__dirname, "../fixtures/vacancy-golden.json");
const golden = JSON.parse(fs.readFileSync(FIXTURE, "utf-8")) as Golden;

/** The contract's tolerance, read from the file so the two cannot drift (see the header). */
const TOLERANCE = golden.tolerance;

// --- the real corpus, the same bytes both stacks use ----------------------------------

const CORPUS_ASSET = path.resolve(__dirname, "../../public/static-data/lex/corpus.json");
const CORPUS = (JSON.parse(fs.readFileSync(CORPUS_ASSET, "utf-8")) as LexCorpusAsset).text;
const CORPUS_TYPES = new Set(tokenize(CORPUS));
const DOMAIN = vacancyDomain(CORPUS_TYPES);
/** The corpus's per-type occurrence counts — the frequency source `mint = "swap"` ranks by. */
const COUNTS = typeCounts(tokenize(CORPUS));
const BUDGET_WORDS = dolchBudget("full");

const sha256 = (s: string): string => createHash("sha256").update(s, "utf8").digest("hex");

/** The exporter's canonical form for a map digest: `stem\tnonce\n`, stems ASCII-ascending. */
function mappingSha256(mapping: ReadonlyMap<string, string>): string {
  const stems = [...mapping.keys()].sort();
  return sha256(stems.map((s) => `${s}\t${mapping.get(s)}\n`).join(""));
}

function paramsOf(c: GoldenCase): VacancyParams {
  return vacancyParams({
    p: c.params.p,
    seed: c.params.seed,
    consistent: c.params.consistent,
    matchProsody: c.params.matchProsody,
    revealAfter: c.params.revealAfter,
    keep: c.params.keep,
    mint: c.params.mint,
  });
}

/**
 * A FRESH map per case, always. Under `consistent = false` the rewrite writes the stress
 * pattern of every form it mints onto `vmap.mintedStress`, so a map shared between cases
 * would score one case's text against another case's minted patterns. The exporter builds
 * fresh maps for the controls for the same reason; doing it for every case here also
 * proves that reuse is irrelevant in the mapped condition.
 */
function mapFor(params: VacancyParams): VacancyMap {
  // `typeCounts` is passed unconditionally. `mint = "nonce"` ignores it — the nonce map is a
  // pure function of `(domain, seed, matchProsody)`, and every pre-existing case in this
  // fixture proves it by still matching — while `mint = "swap"` needs it and throws without
  // it. Passing it always is what keeps the two call sites from differing by what one of
  // them remembered, which is §5.2's whole objection to an optional `avoid`.
  return buildVacancyMap(DOMAIN, params, COUNTS);
}

/** The fixture's own reading of a field a `knownDivergence` block names. */
function goldenField(gc: GoldenCase, field: string): string | number | boolean {
  if (field.startsWith("stats.")) {
    const name = field.slice("stats.".length);
    const value = gc.stats[name];
    if (value === undefined) throw new Error(`vacancy-golden.json: no stat ${name}`);
    return value;
  }
  if (field === "head400") return gc.head400;
  if (field === "vacatedSha256") return gc.vacatedSha256;
  if (field === "vacatedChars") return gc.vacatedChars;
  throw new Error(`vacancy-golden.json: unknown divergence field ${field}`);
}

/** Every float in this fixture is order-1 or smaller, so absolute deviation is the honest read. */
const deviations: { what: string; dev: number }[] = [];
function expectClose(actual: number, expected: number, what: string): void {
  const dev = Math.abs(actual - expected);
  deviations.push({ what, dev });
  expect(dev, `${what}: ${actual} vs golden ${expected}`).toBeLessThanOrEqual(TOLERANCE);
}

/** The §10 fields that are exact integers or booleans, and must compare with `toBe`. */
const EXACT_STATS = [
  "domainTypesTotal",
  "domainTypesEligible",
  "domainTypesVacated",
  "corpusTypesTotal",
  "corpusTypesEligible",
  "corpusTypesVacated",
  "stemsTotal",
  "stemsVacated",
  "tokensTotal",
  "tokensVacated",
  "bijective",
  "imageSize",
  "remintRounds",
] as const;

/** The §10 fields that are means, and are the ONLY things `tolerance` applies to. */
const FLOAT_STATS = [
  "meanSyllablesBefore",
  "meanSyllablesAfter",
  "meanAnapestBefore",
  "meanAnapestAfter",
  "stressFromTableBefore",
  "stressFromTableAfter",
  "stressFromMintedBefore",
  "stressFromMintedAfter",
  "stressFromRuleBefore",
  "stressFromRuleAfter",
] as const;

// --- provenance -----------------------------------------------------------------------

describe("the fixture is the one this test was written against", () => {
  it("declares its format, contract, tolerance and provenance", () => {
    expect(golden.format).toBe("vacancy-golden-v2");
    expect(golden.contract).toBe("specs/007-vacancy-transform-field/architecture.md");
    expect(golden.command).toBe("python scripts/export_vacancy_golden.py");
    expect(golden.git_sha).toMatch(/^[0-9a-f]{40}$/);
    expect(golden.generated).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    expect(TOLERANCE).toBeGreaterThan(0);
    expect(TOLERANCE).toBeLessThanOrEqual(1e-5);
  });

  it("was generated from the same corpus bytes this engine is reading", () => {
    // Not a formality: every nonce, every count and every digest below is a function of
    // these bytes, so a fixture built from a different corpus would fail everywhere at
    // once with no indication of why.
    expect(sha256(CORPUS)).toBe(golden.corpus.sha256);
    expect(CORPUS.length).toBe(golden.corpus.chars);
    expect(tokenize(CORPUS).length).toBe(golden.corpus.tokens);
    expect(CORPUS_TYPES.size).toBe(golden.corpus.corpusTypes);
    expect(DOMAIN.length).toBe(golden.corpus.domainSize);
    expect(golden.corpus.budget).toBe("dolch/full");
    expect(BUDGET_WORDS.length).toBe(golden.corpus.budgetSize);
  });
});

// --- 1. u(stem), exactly ---------------------------------------------------------------

describe("u(stem) is THE SAME double in both languages (§4, departure 2)", () => {
  const keep = effectiveKeepSet([]);

  it("pins 24 stems spanning eligible/ineligible and both budgets", () => {
    expect(golden.stems).toHaveLength(24);
    // The span §11 asks for is a property of the list, so it is asserted rather than
    // assumed: a fixture of 24 ordinary words would pin nothing about the eligibility test.
    expect(golden.stems.some((s) => s.eligible)).toBe(true);
    expect(golden.stems.some((s) => !s.eligible)).toBe(true);
    expect(golden.stems.some((s) => s.inDolchFull)).toBe(true);
    expect(golden.stems.some((s) => s.inCorpus && !s.inDolchFull)).toBe(true);
    expect(golden.stems.some((s) => !s.inCorpus && s.inDolchFull)).toBe(true);
  });

  for (const entry of golden.stems) {
    it(`${entry.stem}: exact u at both seeds, and the same eligibility verdict`, () => {
      // `toBe` on a double is deliberate. The `>> 11` in `vacancyU` exists precisely so
      // that this is bit-exact; a tolerance here would hide the bug it was added to fix.
      expect(vacancyU(entry.stem, 0)).toBe(entry.u["0"]);
      expect(vacancyU(entry.stem, 7)).toBe(entry.u["7"]);
      const [stem, suffix] = stemAndSuffix(entry.stem);
      expect(stem).toBe(entry.stemOf);
      expect(suffix).toBe(entry.suffixOf);
      expect(isEligible(stem, keep)).toBe(entry.eligible);
      expect(DOMAIN.includes(entry.stem)).toBe(entry.inDomain);
      expect(CORPUS_TYPES.has(entry.stem)).toBe(entry.inCorpus);
      expect(BUDGET_WORDS.includes(entry.stem)).toBe(entry.inDolchFull);
    });
  }
});

// --- 2. the maps ------------------------------------------------------------------------

describe("the stem -> nonce map (§5.2)", () => {
  for (const gm of golden.maps) {
    it(`${gm.label}: reproduces Python's assignment`, () => {
      const params = vacancyParams({
        seed: gm.seed,
        matchProsody: gm.matchProsody,
        mint: gm.mint,
        // The control labels differ from the mapped condition only in knobs that do not
        // reach minting, so the map is a pure function of (domain, seed, matchProsody);
        // building it from the seed and the flag alone is itself part of the claim.
      });
      const vmap = mapFor(params);
      expect(vmap.remintRounds).toBe(gm.remintRounds);
      expect(vmap.bijective).toBe(gm.bijective);
      expect(vmap.injectiveAtEveryP).toBe(gm.injectiveAtEveryP);
      expect(vmap.imageSize).toBe(gm.imageSize);
      expect(vmap.domain.size).toBe(gm.domainSize);
      expect(vmap.mapping.size).toBe(gm.mappingSize);
      expect(mappingSha256(vmap.mapping)).toBe(gm.mappingSha256);

      if (gm.mapping !== null) {
        // The full map, pair by pair — §11 asks for every one at seeds 0 and 7. Both
        // directions, so neither a missing stem nor an extra one can pass.
        const expectedStems = Object.keys(gm.mapping);
        expect(expectedStems).toHaveLength(vmap.mapping.size);
        const mismatched: string[] = [];
        for (const [stem, nonce] of Object.entries(gm.mapping)) {
          if (vmap.mapping.get(stem) !== nonce) {
            mismatched.push(`${stem}: ${vmap.mapping.get(stem)} != ${nonce}`);
          }
        }
        expect(mismatched).toEqual([]);
        for (const stem of vmap.mapping.keys()) expect(gm.mapping[stem]).toBeDefined();
      }
      if (gm.sampleNonces !== undefined) {
        for (const [stem, nonce] of Object.entries(gm.sampleNonces)) {
          expect(vmap.mapping.get(stem) ?? null).toBe(nonce);
        }
      }
    });
  }
});

// --- 3-4, 6-8. the measured cases -------------------------------------------------------

describe("the vacated corpus, its statistics and its id stream", () => {
  for (const gc of golden.cases) {
    it(`${gc.label}: matches Python`, () => {
      const params = paramsOf(gc);
      const vmap = mapFor(params);
      // Order matters and it is Python's: the rewrite runs first, because under
      // `consistent = false` it registers the minted stress patterns that the statistics
      // then score the vacated side with.
      const vacated = vacateText(CORPUS, vmap, params);
      const stats: VacancyStats = vacancyStats(CORPUS, vacated, vmap, params);

      // A field the fixture flags as divergent is asserted against the MEASURED TypeScript
      // reading, AND its Python reading is asserted to still differ. Two exact assertions,
      // not a widened tolerance and not a skip: either stack changing fails one of them.
      const diverging = new Map((gc.knownDivergence?.fields ?? []).map((f) => [f.field, f]));
      const consumed = new Set<string>();
      function reference(field: string): string | number | boolean {
        const d = diverging.get(field);
        if (d === undefined) return goldenField(gc, field);
        consumed.add(field);
        expect(goldenField(gc, field), `${gc.label}.${field} (python reading)`).toBe(d.python);
        expect(d.python).not.toBe(d.typescript);
        return d.typescript;
      }

      // §11: strings compare EXACTLY.
      expect(vacated.slice(0, 400), `${gc.label}.head400`).toBe(reference("head400"));
      expect(vacated.length, `${gc.label}.vacatedChars`).toBe(reference("vacatedChars"));
      expect(sha256(vacated), `${gc.label}.vacatedSha256`).toBe(reference("vacatedSha256"));

      for (const field of EXACT_STATS) {
        expect(stats[field], `${gc.label}.${field}`).toBe(reference(`stats.${field}`));
      }
      for (const field of FLOAT_STATS) {
        expectClose(stats[field], reference(`stats.${field}`) as number, `${gc.label}.${field}`);
      }
      // No stale exemption may sit in the fixture unread.
      expect([...consumed].sort()).toEqual([...diverging.keys()].sort());
      // The three-way stress split is token-weighted and sums to 1 on each side (§10).
      expectClose(
        stats.stressFromTableAfter + stats.stressFromMintedAfter + stats.stressFromRuleAfter,
        1,
        `${gc.label}.stressSplitAfter sums to 1`,
      );

      // §11 stability: the surface form of each pinned stem at this `p`.
      if (gc.stemForms !== null) {
        for (const [stem, form] of Object.entries(gc.stemForms)) {
          expect(transformWord(stem, vmap, params), `${gc.label}.stemForms.${stem}`).toBe(form);
        }
      }

      // §7.2 / §7.3: the id stream under the MAPPED vocabulary.
      if (gc.idStream === null) {
        expect(gc.mapVocabWordsRejects).toBe(true);
        // Both stacks refuse: a mapped vocabulary in a control condition would be a word
        // list matching no corpus, built without error.
        expect(() => mapVocabWords(BUDGET_WORDS, vmap, params)).toThrow();
      } else {
        expect(gc.mapVocabWordsRejects).toBe(false);
        const mapped = mapVocabWords(BUDGET_WORDS, vmap, params);
        expect(mapped).toHaveLength(BUDGET_WORDS.length);
        expect(sha256(mapped.join("\n"))).toBe(gc.idStream.mappedWordsSha256);
        const ids = tokenStream(vacated, new LexVocab(mapped, "dolch", "full"));
        expect(ids.length).toBe(gc.idStream.length);
        expect(ids.slice(0, 16)).toEqual(gc.idStream.first16);
        expect(ids.slice(-16)).toEqual(gc.idStream.last16);
        expect(sha256(ids.join(","))).toBe(gc.idStream.digest);
      }
    });
  }
});

// --- 5. nesting, as explicit sets (SC-701) ---------------------------------------------

describe("nesting is a structural fact, checked against explicit sets (SC-701)", () => {
  const gn = golden.nesting;
  const vmap = mapFor(vacancyParams({ seed: gn.seed }));

  function vacatedStems(p: number): string[] {
    const out: string[] = [];
    for (const stem of vmap.mapping.keys()) if (vacancyU(stem, gn.seed) < p) out.push(stem);
    return out.sort();
  }

  for (const level of gn.levels) {
    it(`p = ${level.p}: the vacated stem set is exactly Python's ${level.stems.length}`, () => {
      expect(vacatedStems(level.p)).toEqual(level.stems);
    });
  }

  it("each level contains the one below it", () => {
    for (let i = 1; i < gn.levels.length; i++) {
      const smaller = new Set(gn.levels[i - 1].stems);
      const larger = new Set(gn.levels[i].stems);
      expect(larger.size).toBeGreaterThan(smaller.size);
      for (const stem of smaller) {
        expect(larger.has(stem), `${stem} vacated at ${gn.levels[i - 1].p} but not later`).toBe(
          true,
        );
      }
    }
    // At p = 1 every eligible stem vacates, since u ∈ [0, 1) by construction (§10).
    const top = gn.levels[gn.levels.length - 1];
    expect(top.p).toBe(1);
    expect(top.stems).toHaveLength(vmap.mapping.size);
  });
});

// --- 6. stability across p (SC-702) -----------------------------------------------------

describe("a stem's nonce is identical at every p where it is vacated (SC-702)", () => {
  for (const gm of golden.maps.filter((m) => m.mapping !== null)) {
    it(`${gm.label}: the pinned stems never change form as p grows`, () => {
      const cases = golden.cases.filter((c) => c.map === gm.label && c.stemForms !== null);
      expect(cases.length).toBeGreaterThan(1);
      const seen = new Map<string, string>();
      for (const gc of cases) {
        const params = paramsOf(gc);
        const vmap = mapFor(params);
        for (const stem of Object.keys(gc.stemForms as Record<string, string>)) {
          const form = transformWord(stem, vmap, params);
          if (form === stem) continue; // not vacated at this p — nothing to be stable about
          const previous = seen.get(stem);
          if (previous !== undefined) expect(form).toBe(previous);
          seen.set(stem, form);
        }
      }
      // The pinned list must actually exercise the property, or this describe is vacuous.
      expect(seen.size).toBeGreaterThan(0);
    });
  }
});

// --- 7. the invariance theorem, as data (SC-703) ---------------------------------------

describe("the id stream is unchanged by vacancy at every p (§7.3, SC-703)", () => {
  it("every mapped-condition case has the SAME token-id digest", () => {
    const withStream = golden.cases.filter((c) => c.idStream !== null);
    // Both seeds, both matchProsody settings, every p — one digest.
    expect(withStream.length).toBeGreaterThanOrEqual(16);
    const digests = new Set(withStream.map((c) => (c.idStream as GoldenIdStream).digest));
    const lengths = new Set(withStream.map((c) => (c.idStream as GoldenIdStream).length));
    expect(digests.size).toBe(1);
    expect(lengths.size).toBe(1);
    expect(withStream.some((c) => c.params.seed === 7)).toBe(true);
    expect(withStream.some((c) => !c.params.matchProsody)).toBe(true);
    expect(withStream.some((c) => c.params.p === 1)).toBe(true);
  });

  it("and that digest is the UNVACATED corpus's own stream", () => {
    // The theorem is that relabelling the vocabulary alongside the corpus leaves training
    // bit-identical, so the p = 0 stream — plain English, plain Dolch — must be it.
    const ids = tokenStream(CORPUS, new LexVocab(BUDGET_WORDS, "dolch", "full"));
    const golden0 = golden.cases.find((c) => c.idStream !== null)?.idStream as GoldenIdStream;
    expect(sha256(ids.join(","))).toBe(golden0.digest);
    expect(ids.length).toBe(golden0.length);
  });
});

// --- 8. the controls really are controls -----------------------------------------------

describe("the control conditions are present and behave as controls (§7.1, SC-705)", () => {
  it("both controls and both matchProsody settings are pinned", () => {
    const labels = golden.cases.map((c) => c.label);
    expect(labels).toContain("control-inconsistent");
    expect(labels).toContain("control-reveal-after-2");
    expect(golden.cases.some((c) => !c.params.consistent)).toBe(true);
    expect(golden.cases.some((c) => c.params.revealAfter > 0)).toBe(true);
    expect(golden.cases.some((c) => c.params.matchProsody)).toBe(true);
    expect(golden.cases.some((c) => !c.params.matchProsody)).toBe(true);
  });

  it("matchProsody = false really mints a different map", () => {
    const withProsody = golden.maps.find((m) => m.label === "seed0");
    const without = golden.maps.find((m) => m.label === "seed0-noprosody");
    expect(withProsody?.mappingSha256).not.toBe(without?.mappingSha256);
  });

  it("reveal_after leaves fewer tokens vacated than the pure case at the same p", () => {
    const pure = golden.cases.find((c) => c.label === "seed0-p0.7");
    const reveal = golden.cases.find((c) => c.label === "control-reveal-after-2");
    expect(reveal?.params.p).toBe(pure?.params.p);
    expect(reveal?.stats.tokensVacated as number).toBeLessThan(pure?.stats.tokensVacated as number);
  });

  it("no divergence remains, and any that appeared would still be constrained", () => {
    // The two stacks now agree on every case, so this list is EMPTY — asserted, because a
    // fixture that quietly reacquired an exemption would look exactly like a green run.
    const flagged = golden.cases.filter((c) => c.knownDivergence !== undefined);
    expect(flagged.map((c) => c.label)).toEqual([]);

    // The rest of this test is the constraint the mechanism carries, kept live for the day
    // it is needed again: a divergence may appear only on a CONTROL case, it must carry the
    // explanation and the status, and it may never cover a count the control exists to
    // produce. A mapped-condition case acquiring one would mean the invariance theorem's
    // own arm had stopped agreeing.
    for (const gc of flagged) {
      const d = gc.knownDivergence as GoldenDivergence;
      expect(gc.params.consistent && gc.params.revealAfter === 0).toBe(false);
      expect(d.cause.length).toBeGreaterThan(80);
      expect(d.status).toContain("neither implementation was modified");
      expect(d.fields.length).toBeGreaterThan(0);
      for (const f of d.fields) expect(f.python).not.toBe(f.typescript);
    }
    // The counts a control exists to produce must agree in BOTH stacks — a divergence there
    // would mean SC-705's measurement itself had moved, which no exemption may cover.
    for (const gc of flagged) {
      const names = new Set((gc.knownDivergence as GoldenDivergence).fields.map((f) => f.field));
      expect(names.has("stats.tokensVacated")).toBe(false);
      expect(names.has("stats.stemsVacated")).toBe(false);
      expect(names.has("stats.domainTypesVacated")).toBe(false);
    }
  });

  it("consistent = false holds the vacancy rate but destroys the identity", () => {
    const pure = golden.cases.find((c) => c.label === "seed0-p0.7");
    const control = golden.cases.find((c) => c.label === "control-inconsistent");
    // Same rate — that is what makes it a control and not just a different transform.
    expect(control?.stats.tokensVacated).toBe(pure?.stats.tokensVacated);
    // Different text, because each occurrence gets its own type.
    expect(control?.vacatedSha256).not.toBe(pure?.vacatedSha256);
  });

  it("consistent = false vacates EVERYTHING at p = 1, seed 7 — the `tak` regression", () => {
    // §5.8, condition B on the per-occurrence path. `tak` (the stem of `taking`) once minted
    // the nonce `tak` at seed 7, so `Taking -> Taking` and one token silently survived the
    // transform: 1921 corpus types and 8201 tokens against the consistent path's 1922/8202.
    // A control whose vacancy rate is not the stated rate is not a control, so the identity
    // §10 states at `p = 1` — every eligible type vacates — has to hold here too.
    const control = golden.cases.find((c) => c.label === "control-inconsistent-seed7");
    const pure = golden.cases.find((c) => c.label === "seed7-p1.0");
    expect(control).toBeDefined();
    expect(control?.params.consistent).toBe(false);
    expect(control?.params.p).toBe(1);
    expect(control?.stats.corpusTypesVacated).toBe(1922);
    expect(control?.stats.tokensVacated).toBe(8202);
    expect(control?.stats.corpusTypesVacated).toBe(control?.stats.corpusTypesEligible);
    // The consistent path at the same seed and `p` reads the same counts; only the text
    // differs, which is exactly what this control is for.
    expect(control?.stats.corpusTypesVacated).toBe(pure?.stats.corpusTypesVacated);
    expect(control?.stats.tokensVacated).toBe(pure?.stats.tokensVacated);
    expect(control?.vacatedSha256).not.toBe(pure?.vacatedSha256);
  });
});

afterAll(() => {
  if (deviations.length === 0) return;
  const worst = deviations.reduce((a, b) => (b.dev > a.dev ? b : a));
  const nonZero = deviations.filter((d) => d.dev > 0).length;
  console.log(
    `vacancy golden: ${deviations.length} float comparisons, ${nonZero} non-zero, ` +
      `worst |Δ| = ${worst.dev.toExponential(3)} (${worst.what}), tolerance ${TOLERANCE}`,
  );
});
